import type { PracticeCase, WarningLabel } from "@/lib/types/case";

export const STATIC_CASES: PracticeCase[] = [
  {
    id: "case-1",
    caseNumber: 1,
    title: "Case 1 — Erythromycin 250mg",
    patientLookup: {
      requiresNewPatient: false,
      existingPatientSeedId: "patient-john-smith-abbotsford",
      prescriptionPatient: {
        name: "JOHN SMITH",
        dateOfBirth: "14/03/1965",
        address: "20 TRENERRY CRESCENT, ABBOTSFORD 3067",
        mcare: "MCare 3333-00000-11  to 11/2020",
      },
    },
    price: "$13.01",
    doctor: "WILLIS, HARRY",
    prescriberNo: "8015996",
    prescriberPool: ["prescriber-willis-harry", "prescriber-chen-linda", "prescriber-watson-emily", "prescriber-kowalski-anna", "prescriber-bradley-tom"],
    date: "27/06/17",
    scriptType: "N — NHS",
    items: [
      {
        drug: "ERYTHROMYCIN (MAYNE PHARMA) CAP 250MG",
        prescribedProductType: "brand",
        genericSubstitutionAllowed: false,
        correctDrugSeedId: "erythromycin-mayne-cap-250",
        directions: "Take ONE capsule tds",
        repeats: "1",
        qty: "25",
        price2: "$20.86",
        correctWarnings: ["Take with food or milk", "Complete the full course", "May cause nausea"],
        drugDetails: {
          name: "ERYTHROMYCIN (G)",
          schedule: "S4",
          pbs: "NHS: 1404X",
          pbsClass: "Macrolides",
          claimable: "Not Claimable",
          f2t: "F2T",
          manufacturer: "Mayne Products Pty Ltd",
          cost: "$4.78",
          retail: "$15.34",
          cmi: true,
          newDrug: true,
          warn1: "PDL Warn: Similar Names",
          warn2: "PDL Warn: Caution Strengths",
        },
      },
    ],
    errors: [
      "Patient history shows this course (25 capsules, three times daily — about an 8-day supply) was last dispensed on 23/06/17, only 4 days before this presentation. The repeat is being requested well before the previous course should have run out.",
      "Hold supply and contact the prescriber to confirm why the patient needs more erythromycin this early before dispensing the repeat.",
    ],
    expectedDecision: "hold_contact_prescriber",
    tip: "Erythromycin is a macrolide antibiotic. Before relying on the printed repeats, always check the patient's dispensing history: work out how long the previous supply should have lasted from the quantity and directions, and compare that against the last fill date. A repeat requested well before the prior course should have run out needs prescriber clarification, not routine dispensing.",
  },
  {
    id: "case-2",
    caseNumber: 2,
    title: "Case 2 — Warfarin 5mg",
    patientLookup: {
      requiresNewPatient: false,
      existingPatientSeedId: "patient-margaret-jones-fitzroy",
      prescriptionPatient: {
        name: "MARGARET JONES",
        dateOfBirth: "22/06/1948",
        address: "44 OAK STREET, FITZROY 3065",
        mcare: "MCare 4444-11111-22  to 06/2021",
      },
    },
    price: "$6.50",
    doctor: "CHEN, LINDA",
    prescriberNo: "7029384",
    prescriberPool: ["prescriber-willis-harry", "prescriber-chen-linda", "prescriber-watson-emily", "prescriber-kowalski-anna", "prescriber-bradley-tom"],
    date: "27/06/17",
    scriptType: "N — NHS",
    items: [
      {
        drug: "WARFARIN (COUMADIN) TAB 5MG",
        prescribedProductType: "brand",
        genericSubstitutionAllowed: false,
        correctDrugSeedId: "warfarin-coumadin-tab-5",
        directions: "Take as directed",
        repeats: "2",
        qty: "50",
        price2: "$6.50",
        correctWarnings: [
          "Avoid alcohol",
          "Regular blood tests required",
          "Do not take aspirin/NSAIDs without advice",
        ],
        drugDetails: {
          name: "WARFARIN (G)",
          schedule: "S4",
          pbs: "NHS: 1055C",
          pbsClass: "Anticoagulants",
          claimable: "Claimable",
          f2t: "",
          manufacturer: "Aspen Pharma",
          cost: "$3.20",
          retail: "$6.50",
          cmi: true,
          newDrug: false,
          warn1: "PDL Warn: Narrow Therapeutic Index",
          warn2: "PDL Warn: Confirm current INR monitoring and dose plan",
        },
      },
    ],
    errors: [],
    expectedDecision: "dispense",
    tip: "Warfarin has a narrow therapeutic index. Confirm the current dose plan and INR follow-up, check interacting medicines, and use the current PBS item listing rather than applying a blanket repeat rule.",
  },
  {
    id: "case-3",
    caseNumber: 3,
    title: "Case 3 — Amoxycillin Suspension 250mg/5mL",
    patientLookup: {
      requiresNewPatient: true,
      expectedNewPatient: {
        surname: "HENDERSON",
        firstname: "LIAM",
        title: "MASTER",
        sex: "M",
        dateOfBirth: "12/05/2009",
        address: "7 MAPLE DRIVE",
        suburb: "NORTHCOTE",
        postcode: "3070",
        medicareCard: "5511-22233-1",
        medicareValidTo: "12/2022",
      },
      prescriptionPatient: {
        name: "LIAM HENDERSON",
        dateOfBirth: "12/05/2009",
        address: "7 MAPLE DRIVE, NORTHCOTE 3070",
        mcare: "MCare 5511-22233-1  to 12/2022",
      },
    },
    price: "$5.40",
    doctor: "WATSON, EMILY",
    prescriberNo: "3847291",
    prescriberPool: ["prescriber-willis-harry", "prescriber-chen-linda", "prescriber-watson-emily", "prescriber-kowalski-anna", "prescriber-bradley-tom"],
    date: "27/06/17",
    scriptType: "N — NHS",
    items: [
      {
        drug: "AMOXYCILLIN (AN) SUSP 250MG/5ML",
        prescribedProductType: "brand",
        genericSubstitutionAllowed: false,
        correctDrugSeedId: "amoxycillin-an-susp-250",
        directions: "Give 10mL tds for 10 days",
        repeats: "0",
        qty: "300mL",
        price2: "$5.40",
        correctWarnings: [
          "Shake well before use",
          "Keep refrigerated",
          "Complete the full course",
        ],
        drugDetails: {
          name: "AMOXICILLIN SUSP (G)",
          schedule: "S4",
          pbs: "NHS: 4244H",
          pbsClass: "Penicillins",
          claimable: "Claimable",
          f2t: "",
          manufacturer: "Alphapharm Pty Ltd",
          cost: "$2.10",
          retail: "$5.40",
          cmi: true,
          newDrug: false,
          warn1: "PDL: Reconstitute with water",
          warn2: "PDL: Paediatric dose weight-based",
        },
      },
    ],
    errors: [],
    expectedDecision: "dispense",
    tip: "For paediatric liquids, verify the dose using the documented weight, concentration, indication and current paediatric reference. Reconstitution, storage and beyond-use instructions must come from the exact product selected and must support completion of the prescribed course.",
  },
  {
    id: "case-4",
    caseNumber: 4,
    title: "Case 4 — Temazepam 10mg",
    patientLookup: {
      requiresNewPatient: false,
      existingPatientSeedId: "patient-david-park-hawthorn",
      prescriptionPatient: {
        name: "DAVID PARK",
        dateOfBirth: "08/11/1971",
        address: "31 RIVERVIEW RD, HAWTHORN 3122",
        mcare: "MCare 6622-33441-1  to 09/2020",
      },
    },
    price: "Private",
    doctor: "KOWALSKI, ANNA",
    prescriberNo: "9012847",
    prescriberPool: ["prescriber-willis-harry", "prescriber-chen-linda", "prescriber-watson-emily", "prescriber-kowalski-anna", "prescriber-bradley-tom"],
    date: "27/06/17",
    scriptType: "P — Private",
    items: [
      {
        drug: "TEMAZE TAB 10MG",
        prescribedProductType: "brand",
        genericSubstitutionAllowed: false,
        correctDrugSeedId: "temazepam-temaze-tab-10",
        directions: "Take 1-2 tabs nocte prn",
        repeats: "0",
        qty: "50",
        price2: "Private",
        correctWarnings: [
          "May cause drowsiness",
          "Avoid alcohol",
          "Avoid driving/machinery",
          "Do not stop suddenly",
        ],
        drugDetails: {
          name: "TEMAZEPAM (G)",
          schedule: "S4 — monitored in SafeScript (VIC)",
          pbs: "Private only",
          pbsClass: "Benzodiazepines — Hypnotics",
          claimable: "Not PBS Claimable",
          f2t: "",
          manufacturer: "Alphapharm",
          cost: "Private",
          retail: "Private",
          cmi: true,
          newDrug: false,
          warn1: "PDL: Sedation and dependence risk — pharmacist review",
          warn2: "PDL: SafeScript-monitored medicine in Victoria",
        },
      },
    ],
    errors: [
      "The quantity and dose range require pharmacist assessment before supply.",
      "The documented history of alcohol dependence increases sedation, dependence and misuse risk. Hold the supply and clarify the treatment plan with the prescriber.",
    ],
    expectedDecision: "hold_contact_prescriber",
    tip: "Temazepam is Schedule 4, not Schedule 8. In Victoria it is monitored in SafeScript. Review indication, duration, dose, quantity, other sedatives and substance-use history, then document any prescriber clarification before supply.",
  },
  {
    id: "case-5",
    caseNumber: 5,
    title: "Case 5 — Metformin 1000mg",
    patientLookup: {
      requiresNewPatient: false,
      existingPatientSeedId: "patient-carol-simmons-carlton",
      prescriptionPatient: {
        name: "CAROL SIMMONS",
        dateOfBirth: "23/04/1959",
        address: "78 LYGON ST, CARLTON 3053",
        mcare: "MCare 7733-44552-3  to 04/2023",
      },
    },
    price: "$6.50",
    doctor: "YUEN, RICHARD",
    prescriberNo: "5512847",
    prescriberPool: ["prescriber-yuen-richard", "prescriber-chen-linda", "prescriber-willis-harry", "prescriber-kowalski-anna"],
    date: "27/06/17",
    scriptType: "N — NHS",
    items: [
      {
        drug: "METFORMIN (AN) TAB 1000MG",
        prescribedProductType: "brand",
        genericSubstitutionAllowed: false,
        correctDrugSeedId: "metformin-an-tab-1000",
        directions: "Take ONE tab bd pc",
        repeats: "5",
        qty: "60",
        price2: "$6.50",
        correctWarnings: ["Take with food or milk", "Regular blood tests required"],
        drugDetails: {
          name: "METFORMIN (G)",
          schedule: "S4",
          pbs: "NHS: 1162L",
          pbsClass: "Biguanides — Antidiabetics",
          claimable: "Claimable",
          f2t: "",
          manufacturer: "Sandoz",
          cost: "$2.80",
          retail: "$6.50",
          cmi: true,
          newDrug: false,
          warn1: "PDL: Monitor renal function",
          warn2: "PDL: Drug interaction — cimetidine",
        },
      },
    ],
    errors: [
      "⚠ DRUG INTERACTION: Cimetidine inhibits renal tubular secretion of metformin — increased metformin levels. Monitor for lactic acidosis.",
      "⚠ eGFR 58 — use with caution. Metformin contraindicated if eGFR <30. Monitor renal function.",
    ],
    expectedDecision: "hold_contact_prescriber",
    tip: "Cimetidine is an organic cation and inhibits renal tubular secretion of metformin (also a cation), increasing metformin AUC by ~40%. Combined with mild CKD (eGFR 58), risk of metformin accumulation and lactic acidosis is elevated. Recommend contacting prescriber.",
  },
  {
    id: "case-6",
    caseNumber: 6,
    title: "Case 6 — Doxycycline 50mg",
    patientLookup: {
      requiresNewPatient: true,
      expectedNewPatient: {
        surname: "CHANG",
        firstname: "FIONA",
        title: "MS",
        sex: "F",
        dateOfBirth: "15/03/1998",
        address: "22 CHAPEL ST",
        suburb: "PRAHRAN",
        postcode: "3181",
        medicareCard: "8844-55663-2",
        medicareValidTo: "07/2024",
      },
      prescriptionPatient: {
        name: "FIONA CHANG",
        dateOfBirth: "15/03/1998",
        address: "22 CHAPEL ST, PRAHRAN 3181",
        mcare: "MCare 8844-55663-2  to 07/2024",
      },
    },
    price: "$13.01",
    doctor: "BRADLEY, TOM",
    prescriberNo: "6623941",
    prescriberPool: ["prescriber-willis-harry", "prescriber-chen-linda", "prescriber-watson-emily", "prescriber-kowalski-anna", "prescriber-bradley-tom"],
    date: "27/06/17",
    scriptType: "N — NHS",
    items: [
      {
        drug: "DOXYCYCLINE (AN) TAB 50MG",
        prescribedProductType: "brand",
        genericSubstitutionAllowed: false,
        correctDrugSeedId: "doxycycline-an-tab-50",
        directions: "Take ONE tab bd",
        repeats: "5",
        qty: "60",
        price2: "$13.01",
        correctWarnings: [
          "Take with a full glass of water",
          "Avoid sunlight / use sunscreen",
          "Do not lie down for 30 min after taking",
          "Avoid dairy/antacids within 2 hours",
          "Complete the full course",
        ],
        drugDetails: {
          name: "DOXYCYCLINE (G)",
          schedule: "S4",
          pbs: "NHS: 1678N",
          pbsClass: "Tetracyclines",
          claimable: "Claimable",
          f2t: "",
          manufacturer: "Pfizer",
          cost: "$4.50",
          retail: "$13.01",
          cmi: true,
          newDrug: false,
          warn1: "PDL: Photosensitivity — sunscreen",
          warn2: "PDL: Oesophageal ulceration risk",
        },
      },
    ],
    errors: [],
    expectedDecision: "dispense",
    tip: "Doxycycline counselling should cover administration with water while upright, separation from relevant interacting products, photosensitivity and the intended duration. Do not apply a blanket rule about backup contraception; check the patient's circumstances and a current medicines reference.",
  },
  {
    id: "case-7",
    caseNumber: 7,
    title: "Case 7 — OxyContin MR 20mg",
    patientLookup: {
      requiresNewPatient: false,
      existingPatientSeedId: "patient-peter-morales-richmond",
      prescriptionPatient: {
        name: "PETER MORALES",
        dateOfBirth: "19/08/1963",
        address: "18 BRIDGE ROAD, RICHMOND 3121",
        mcare: "MCare 4928-30177-4  to 08/2028",
      },
    },
    price: "$7.70",
    doctor: "SINGH, AMRITA",
    prescriberNo: "6147283",
    date: "15/07/26",
    scriptType: "N — NHS",
    authority: {
      required: true,
      type: "approval",
      number: "H7421QZ",
      indication: "Severe chronic cancer-related pain in an opioid-tolerant patient",
    },
    items: [
      {
        drug: "OXYCONTIN MR TAB 20MG",
        prescribedProductType: "brand",
        genericSubstitutionAllowed: false,
        correctDrugSeedId: "oxycontin-mr-tab-20",
        directions: "Take ONE tablet every 12 hours",
        repeats: "0",
        qty: "28",
        price2: "$7.70",
        correctWarnings: [
          "May cause drowsiness",
          "Avoid alcohol",
          "Avoid driving/machinery",
          "Swallow whole — do not crush or chew",
          "Keep locked away and out of reach",
        ],
        drugDetails: {
          name: "OXYCONTIN",
          schedule: "S8 — SafeScript monitored (VIC)",
          pbs: "Authority required — verify current item and restriction",
          pbsClass: "Opioid analgesics",
          claimable: "Authority claim",
          f2t: "",
          manufacturer: "Mundipharma Pty Ltd",
          cost: "$18.20",
          retail: "$7.70 patient contribution",
          cmi: true,
          newDrug: false,
          warn1: "S8: authenticate prescription and check SafeScript",
          warn2: "Modified-release tablet: swallow whole",
        },
      },
    ],
    errors: [],
    expectedDecision: "dispense",
    tip: "This is a deliberately documented opioid-tolerant patient. Verify identity, indication, current opioid exposure, authority approval, SafeScript history, dose, quantity and storage. Modified-release oxycodone must be swallowed whole; crushing can release a potentially fatal dose.",
  },
  {
    id: "case-8",
    caseNumber: 8,
    title: "Case 8 — Durogesic Patch 25mcg/h",
    patientLookup: {
      requiresNewPatient: false,
      existingPatientSeedId: "patient-helen-brooks-kew",
      prescriptionPatient: {
        name: "HELEN BROOKS",
        dateOfBirth: "04/02/1945",
        address: "6 WALPOLE STREET, KEW 3101",
        mcare: "MCare 5832-11904-2  to 02/2028",
      },
    },
    price: "$7.70",
    doctor: "SINGH, AMRITA",
    prescriberNo: "6147283",
    date: "15/07/26",
    scriptType: "N — NHS",
    authority: {
      required: true,
      type: "approval",
      number: "H8317FT",
      indication: "Severe chronic pain",
    },
    items: [
      {
        drug: "DUROGESIC PATCH 25MCG/H",
        prescribedProductType: "brand",
        genericSubstitutionAllowed: false,
        correctDrugSeedId: "durogesic-patch-25",
        directions: "Apply ONE patch every 72 hours",
        repeats: "0",
        qty: "5",
        price2: "$7.70",
        correctWarnings: [
          "May cause drowsiness",
          "Avoid alcohol",
          "Avoid driving/machinery",
          "Avoid heat on the patch",
          "Remove old patch before applying a new one",
          "Keep locked away and out of reach",
        ],
        drugDetails: {
          name: "DUROGESIC",
          schedule: "S8 — SafeScript monitored (VIC)",
          pbs: "Authority required — verify current item and restriction",
          pbsClass: "Opioid analgesics",
          claimable: "Authority claim if valid",
          f2t: "",
          manufacturer: "Janssen-Cilag Pty Ltd",
          cost: "$22.00",
          retail: "$7.70 patient contribution",
          cmi: true,
          newDrug: true,
          warn1: "Critical: confirm opioid tolerance before supply",
          warn2: "Heat can increase fentanyl absorption",
        },
      },
    ],
    errors: [
      "The patient is opioid-naive; a 25 microgram/hour fentanyl patch can cause fatal respiratory depression.",
      "Hold supply and urgently clarify the intended analgesic plan with the prescriber.",
    ],
    expectedDecision: "hold_contact_prescriber",
    tip: "Transdermal fentanyl is not a starting opioid for opioid-naive patients. The pharmacist must hold the prescription, authenticate the S8 order, review SafeScript and contact the prescriber. If later supplied, patch counselling must cover old-patch removal, site rotation, heat avoidance, secure storage, disposal and respiratory-depression red flags.",
  },
  {
    id: "case-9",
    caseNumber: 9,
    title: "Case 9 — Dexamfetamine 5mg",
    patientLookup: {
      requiresNewPatient: false,
      existingPatientSeedId: "patient-noah-williams-brunswick",
      prescriptionPatient: {
        name: "NOAH WILLIAMS",
        dateOfBirth: "11/11/2009",
        address: "91 SYDNEY ROAD, BRUNSWICK 3056",
        mcare: "MCare 6741-55029-1  to 11/2028",
      },
    },
    price: "$7.70",
    doctor: "RAO, NISHA",
    prescriberNo: "9911002",
    expectedPrescriberNo: "7812456",
    date: "15/07/26",
    scriptType: "N — NHS",
    authority: {
      required: true,
      type: "streamlined",
      number: "1912",
      indication: "ADHD continuation treatment",
    },
    items: [
      {
        drug: "ASPEN DEXAMFETAMINE TAB 5MG",
        prescribedProductType: "brand",
        genericSubstitutionAllowed: false,
        correctDrugSeedId: "aspen-dexamfetamine-tab-5",
        directions: "Take ONE tablet mane and at noon",
        repeats: "0",
        qty: "100",
        price2: "$7.70",
        correctWarnings: [
          "Avoid driving/machinery",
          "Keep locked away and out of reach",
        ],
        drugDetails: {
          name: "ASPEN DEXAMFETAMINE",
          schedule: "S8 — special Schedule 8 psychostimulant",
          pbs: "Authority required (streamlined) — training code shown on script",
          pbsClass: "Psychostimulants",
          claimable: "Only if prescription and authority details are valid",
          f2t: "",
          manufacturer: "Aspen Pharmacare Australia Pty Ltd",
          cost: "$13.20",
          retail: "$7.70 patient contribution",
          cmi: true,
          newDrug: false,
          warn1: "Authenticate S8 prescription",
          warn2: "Check age, specialist/permit pathway and SafeScript",
        },
      },
    ],
    errors: [
      "The prescriber number printed on the prescription (9911002) does not match Dr Nisha Rao's directory number (7812456).",
      "A Schedule 8 prescription must be authenticated; hold supply and contact the purported prescriber using independently verified details.",
    ],
    expectedDecision: "hold_contact_prescriber",
    tip: "Do not call a telephone number written on a suspicious prescription. Use the established prescriber directory, compare the prescriber number, authenticate the Schedule 8 prescription and document the intervention before any supply decision.",
  },
  {
    id: "case-10",
    caseNumber: 10,
    title: "Case 10 — Methotrexate 10mg",
    patientLookup: {
      requiresNewPatient: false,
      existingPatientSeedId: "patient-grace-lim-box-hill",
      prescriptionPatient: {
        name: "GRACE LIM",
        dateOfBirth: "09/09/1967",
        address: "27 STATION STREET, BOX HILL 3128",
        mcare: "MCare 7250-44810-8  to 09/2029",
      },
    },
    price: "$7.70",
    doctor: "MURPHY, ELLEN",
    prescriberNo: "3481752",
    date: "15/07/26",
    scriptType: "N — NHS",
    items: [
      {
        drug: "METHOTREXATE CIPLA TAB 10MG",
        prescribedProductType: "brand",
        genericSubstitutionAllowed: false,
        correctDrugSeedId: "methotrexate-cipla-tab-10",
        directions: "Take ONE tablet daily",
        repeats: "2",
        qty: "12",
        price2: "$7.70",
        correctWarnings: [
          "Take once weekly on the same day",
          "Regular blood tests required",
          "Do not take aspirin/NSAIDs without advice",
        ],
        drugDetails: {
          name: "METHOTREXATE CIPLA 10",
          schedule: "S4",
          pbs: "Restricted/authority status depends on current item and indication",
          pbsClass: "Antimetabolites / immunomodulators",
          claimable: "Verify current listing",
          f2t: "",
          manufacturer: "Cipla Australia Pty Ltd",
          cost: "$8.30",
          retail: "$7.70 patient contribution",
          cmi: true,
          newDrug: false,
          warn1: "HIGH RISK: weekly dosing",
          warn2: "Check folate plan, pregnancy status and monitoring",
        },
      },
    ],
    errors: [
      "The directions say daily. Low-dose methotrexate for rheumatoid arthritis is normally taken once weekly; daily administration can be fatal.",
      "Do not alter or dispense the prescription without direct prescriber clarification.",
    ],
    expectedDecision: "hold_contact_prescriber",
    tip: "Treat a daily low-dose methotrexate direction as a critical prescribing error. Hold supply, contact the prescriber, verify the intended weekly day and dose, check folic acid and monitoring, then document any lawful correction before dispensing.",
  },
  {
    id: "case-11",
    caseNumber: 11,
    title: "Case 11 — Quilonum SR 450mg",
    patientLookup: {
      requiresNewPatient: false,
      existingPatientSeedId: "patient-rahul-mehta-footscray",
      prescriptionPatient: {
        name: "RAHUL MEHTA",
        dateOfBirth: "29/01/1982",
        address: "14 PAISLEY STREET, FOOTSCRAY 3011",
        mcare: "MCare 8164-33071-5  to 01/2029",
      },
    },
    price: "$7.70",
    doctor: "MURPHY, ELLEN",
    prescriberNo: "3481752",
    date: "15/07/26",
    scriptType: "N — NHS",
    items: [
      {
        drug: "QUILONUM SR TAB 450MG",
        prescribedProductType: "brand",
        genericSubstitutionAllowed: false,
        correctDrugSeedId: "quilonum-sr-tab-450",
        directions: "Take ONE tablet bd",
        repeats: "2",
        qty: "100",
        price2: "$7.70",
        correctWarnings: [
          "Regular blood tests required",
          "Do not take aspirin/NSAIDs without advice",
          "Maintain normal fluid and salt intake",
          "Swallow whole — do not crush or chew",
        ],
        drugDetails: {
          name: "QUILONUM SR",
          schedule: "S4",
          pbs: "Verify current lithium carbonate listing",
          pbsClass: "Mood stabilisers",
          claimable: "Verify current listing",
          f2t: "",
          manufacturer: "GlaxoSmithKline Australia Pty Ltd",
          cost: "$10.90",
          retail: "$7.70 patient contribution",
          cmi: true,
          newDrug: false,
          warn1: "Narrow therapeutic index",
          warn2: "Dehydration and NSAIDs can precipitate toxicity",
        },
      },
    ],
    errors: [
      "The patient reports vomiting and diarrhoea with reduced fluid intake and has started ibuprofen; both can increase lithium toxicity risk.",
      "Hold supply and arrange urgent clinical advice and lithium/renal assessment rather than giving routine continuation advice.",
    ],
    expectedDecision: "hold_contact_prescriber",
    tip: "Lithium toxicity can be triggered by dehydration, renal impairment and interacting medicines including NSAIDs. Symptoms such as worsening tremor, vomiting, diarrhoea, ataxia, confusion or marked drowsiness need urgent assessment.",
  },
  {
    id: "case-12",
    caseNumber: 12,
    title: "Case 12 — Eliquis 5mg",
    patientLookup: {
      requiresNewPatient: false,
      existingPatientSeedId: "patient-evelyn-scott-camberwell",
      prescriptionPatient: {
        name: "EVELYN SCOTT",
        dateOfBirth: "02/12/1942",
        address: "55 BURKE ROAD, CAMBERWELL 3124",
        mcare: "MCare 9073-22581-9  to 12/2028",
      },
    },
    price: "$7.70",
    doctor: "LEE, JONATHAN",
    prescriberNo: "5294061",
    date: "15/07/26",
    scriptType: "N — NHS",
    items: [
      {
        drug: "ELIQUIS TAB 5MG",
        prescribedProductType: "brand",
        genericSubstitutionAllowed: false,
        correctDrugSeedId: "eliquis-tab-5",
        directions: "Take ONE tablet bd",
        repeats: "5",
        qty: "60",
        price2: "$7.70",
        correctWarnings: [
          "Do not stop suddenly",
          "Do not take aspirin/NSAIDs without advice",
          "Report unusual bleeding urgently",
        ],
        drugDetails: {
          name: "ELIQUIS",
          schedule: "S4",
          pbs: "Authority/restriction depends on indication — verify current item",
          pbsClass: "Direct factor Xa inhibitors",
          claimable: "Verify indication and current listing",
          f2t: "",
          manufacturer: "Bristol-Myers Squibb Australia Pty Ltd",
          cost: "$35.40",
          retail: "$7.70 patient contribution",
          cmi: true,
          newDrug: false,
          warn1: "Bleeding-risk medicine",
          warn2: "Check indication-specific dose and renal function",
        },
      },
    ],
    errors: [
      "For atrial fibrillation, the documented age (83 years), weight (54 kg) and serum creatinine (168 micromol/L) meet dose-reduction criteria; the 5 mg twice-daily prescription needs review.",
      "The patient also reports regular naproxen use, increasing bleeding risk. Hold and contact the prescriber.",
    ],
    expectedDecision: "hold_contact_prescriber",
    tip: "Apixaban dosing is indication-specific. For non-valvular atrial fibrillation, verify the current product-information dose-reduction criteria and renal function. Reconcile antiplatelets and NSAIDs, counsel on adherence and bleeding, and provide a procedure/emergency plan.",
  },
  {
    id: "case-13",
    caseNumber: 13,
    title: "Case 13 — Metformin XR 500mg and Sitagliptin 100mg",
    patientLookup: {
      requiresNewPatient: false,
      existingPatientSeedId: "patient-christopher-carruthers-adelaide",
      prescriptionPatient: {
        name: "CHRISTOPHER CARRUTHERS",
        dateOfBirth: "08/01/1978",
        address: "173 OAKENDON STREET, ADELAIDE 5000",
        mcare: "MCare 3656-55648-8  to 12/2028",
      },
    },
    price: "$52.10",
    doctor: "REED, ELLIOT",
    prescriberNo: "7399488",
    date: "18/08/25",
    scriptType: "N — NHS",
    items: [
      {
        drug: "METEX XR ER TAB 500MG",
        prescribedProductType: "generic",
        genericSubstitutionAllowed: true,
        correctDrugSeedId: "metex-xr-tab-500",
        directions: "Take FOUR tablets daily",
        repeats: "5",
        qty: "120",
        price2: "$22.10",
        correctWarnings: [
          "Take with food or milk",
          "Swallow whole — do not crush or chew",
        ],
        drugDetails: {
          name: "METEX XR",
          schedule: "S4",
          pbs: "NHS: 9435N",
          pbsClass: "Biguanides",
          claimable: "Claimable",
          f2t: "F2T",
          manufacturer: "Arrotex Pharmaceuticals Pty Ltd",
          cost: "$12.40",
          retail: "$22.10",
          cmi: true,
          newDrug: false,
          warn1: "PDL Warn: Check release form",
          warn2: "PDL Warn: Not interchangeable with immediate release",
        },
      },
      {
        drug: "JANUVIA TAB 100MG",
        prescribedProductType: "brand",
        genericSubstitutionAllowed: true,
        correctDrugSeedId: "januvia-tab-100",
        directions: "Take ONE tablet daily",
        repeats: "5",
        qty: "28",
        price2: "$30.00",
        correctWarnings: ["May cause nausea"],
        drugDetails: {
          name: "JANUVIA",
          schedule: "S4",
          pbs: "NHS: 11576G",
          pbsClass: "DPP-4 inhibitors",
          claimable: "Streamlined authority required",
          f2t: "",
          manufacturer: "Merck Sharp & Dohme (Australia) Pty Ltd",
          cost: "$21.60",
          retail: "$30.00",
          cmi: true,
          newDrug: false,
          warn1: "PDL Warn: Streamlined authority item",
          warn2: "PDL Warn: Check renal dose band",
        },
      },
    ],
    authority: {
      required: true,
      type: "streamlined",
      number: "7541",
      indication: "Type 2 diabetes — dual oral therapy with metformin",
    },
    errors: [],
    expectedDecision: "dispense",
    tip: "Both items are dispensed on the one prescription and each needs its own label, directions and checks. Metformin XR is an extended-release product and is not interchangeable with immediate-release metformin — it must be swallowed whole. Sitagliptin is a streamlined authority item: transcribe the code from the prescription and check the indication matches the restriction. Confirm the total daily metformin dose (2 g) matches the quantity and directions, and check renal function against the current sitagliptin dose bands.",
  },
];

export const ALL_WARNINGS: WarningLabel[] = [
  { lbl: "18", sig: "L18", text: "Take with food or milk", aliases: ["take with food", "with food", "with meals", "take after food"] },
  { lbl: "5", sig: "L5", text: "Complete the full course", aliases: ["finish the full course", "finish the course", "complete course", "take until finished"] },
  { lbl: "A", sig: "SW", text: "Shake well before use", aliases: ["shake well", "shake before use"] },
  { lbl: "C", sig: "30AC", text: "Keep refrigerated", aliases: ["store in the fridge", "keep in fridge", "refrigerate"] },
  { lbl: "D", sig: "UAF", text: "May cause nausea", aliases: ["may cause stomach upset", "may make you feel sick", "can cause nausea"] },
  { lbl: "E", sig: "UAD", text: "May cause drowsiness", aliases: ["may make you drowsy", "may cause sleepiness", "can cause drowsiness"] },
  { lbl: "F", sig: "ALC", text: "Avoid alcohol", aliases: ["do not drink alcohol", "no alcohol"] },
  { lbl: "G", sig: "DRV", text: "Avoid driving/machinery", aliases: ["do not drive or operate machinery", "avoid driving", "do not drive"] },
  { lbl: "H", sig: "SUN", text: "Avoid sunlight / use sunscreen", aliases: ["avoid sun and use sunscreen", "use sunscreen", "sun sensitivity", "protect from sunlight"] },
  { lbl: "I", sig: "WTR", text: "Take with a full glass of water", aliases: ["take with plenty of water", "full glass of water"] },
  { lbl: "K", sig: "BT", text: "Regular blood tests required", aliases: ["regular blood tests", "blood test monitoring", "requires blood tests"] },
  { lbl: "L", sig: "LYD", text: "Do not lie down for 30 min after taking", aliases: ["stay upright for 30 minutes", "do not lie down for 30 minutes", "remain upright"] },
  { lbl: "M", sig: "DAI", text: "Avoid dairy/antacids within 2 hours", aliases: ["separate dairy and antacids by 2 hours", "avoid antacids within 2 hours", "separate minerals by 2 hours"] },
  { lbl: "N", sig: "STP", text: "Do not stop suddenly", aliases: ["do not stop abruptly", "dont stop suddenly", "do not suddenly stop"] },
  { lbl: "O", sig: "ASP", text: "Do not take aspirin/NSAIDs without advice", aliases: ["avoid aspirin and nsaids", "check before taking ibuprofen", "do not take ibuprofen without advice"] },
  { lbl: "P", sig: "WHO", text: "Swallow whole — do not crush or chew", aliases: ["swallow whole", "do not crush", "do not chew"] },
  { lbl: "Q", sig: "SEC", text: "Keep locked away and out of reach", aliases: ["keep locked away", "secure storage", "keep out of reach"] },
  { lbl: "R", sig: "HTP", text: "Avoid heat on the patch", aliases: ["avoid heat", "no heat packs", "keep patch away from heat"] },
  { lbl: "S", sig: "ROP", text: "Remove old patch before applying a new one", aliases: ["remove old patch", "one patch at a time"] },
  { lbl: "T", sig: "WKY", text: "Take once weekly on the same day", aliases: ["once a week", "weekly", "same day each week"] },
  { lbl: "U", sig: "FLS", text: "Maintain normal fluid and salt intake", aliases: ["keep fluid and salt intake stable", "drink normally", "avoid dehydration"] },
  { lbl: "V", sig: "BLD", text: "Report unusual bleeding urgently", aliases: ["report bleeding", "seek help for bleeding", "unusual bleeding"] },
];

export const ABBREVS: Record<string, string> = {
  od:    "once daily",
  bd:    "twice daily",
  tds:   "three times daily",
  qid:   "four times daily",
  mane:  "in the morning",
  nocte: "at night",
  prn:   "as needed",
  sos:   "when required",
  pc:    "after meals",
  ac:    "before meals",
  cc:    "with food",
  stat:  "immediately",
  cap:   "capsule",
  caps:  "capsules",
  tab:   "tablet",
  tabs:  "tablets",
  susp:  "suspension",
  ml:    "mL",
  mcg:   "micrograms",
  mg:    "milligrams",
};
