import type { PracticeCase, WarningLabel } from "@/lib/types/case";

export const STATIC_CASES: PracticeCase[] = [
  {
    id: "case-1",
    caseNumber: 1,
    title: "Case 1 — Erythromycin 250mg",
    patientLookup: {
      requiresNewPatient: false,
      existingPatientSeedId: "patient-john-smith-abbotsford",
      prescriptionPatient: {
        name: "JOHN SMITH",
        address: "20 TRENERRY CRESCENT, ABBOTSFORD 3067",
        mcare: "MCare 3333-00000-11  to 11/2020",
      },
    },
    price: "$13.01",
    doctor: "WILLIS, HARRY",
    prescriberNo: "8015996",
    date: "27/06/17",
    scriptType: "N — NHS",
    drug: "ERYTHROMYCIN (MAYNE PHARMA) CAP 250MG",
    correctDrugSeedId: "erythromycin-mayne-cap-250",
    directions: "Take ONE capsule tds",
    repeats: "1",
    qty: "25",
    price2: "$20.86",
    correctWarnings: ["Take with food or milk", "Complete the full course", "May cause nausea"],
    errors: [],
    drugDetails: {
      name: "ERYTHROMYCIN (G)",
      schedule: "S4",
      pbs: "NHS: 1404X",
      pbsClass: "Macrolides",
      claimable: "Not Claimable",
      f2t: "F2T",
      manufacturer: "Mayne Products Pty Ltd",
      cost: "$4.78",
      retail: "$15.34",
      cmi: true,
      newDrug: true,
      warn1: "PDL Warn: Similar Names",
      warn2: "PDL Warn: Caution Strengths",
    },
    tip: "Erythromycin is a macrolide antibiotic — safe in penicillin allergy. Take with food to reduce GI upset. Counsel to complete course. Max 1 repeat for antibiotics.",
  },
  {
    id: "case-2",
    caseNumber: 2,
    title: "Case 2 — Warfarin (Error: Repeats)",
    patientLookup: {
      requiresNewPatient: false,
      existingPatientSeedId: "patient-margaret-jones-fitzroy",
      prescriptionPatient: {
        name: "MARGARET JONES",
        address: "44 OAK STREET, FITZROY 3065",
        mcare: "MCare 4444-11111-22  to 06/2021",
      },
    },
    price: "$6.50",
    doctor: "CHEN, LINDA",
    prescriberNo: "7029384",
    date: "27/06/17",
    scriptType: "N — NHS",
    drug: "WARFARIN (COUMADIN) TAB 5MG",
    correctDrugSeedId: "warfarin-coumadin-tab-5",
    directions: "Take as directed",
    repeats: "5",
    qty: "30",
    price2: "$6.50",
    correctWarnings: [
      "Avoid alcohol",
      "Regular blood tests required",
      "Do not take aspirin/NSAIDs without advice",
    ],
    errors: ["Warfarin must NOT have repeats — PBS restriction. Contact prescriber to rewrite."],
    drugDetails: {
      name: "WARFARIN (G)",
      schedule: "S4",
      pbs: "NHS: 1055C",
      pbsClass: "Anticoagulants",
      claimable: "Claimable",
      f2t: "",
      manufacturer: "Aspen Pharma",
      cost: "$3.20",
      retail: "$6.50",
      cmi: true,
      newDrug: false,
      warn1: "PDL Warn: Narrow Therapeutic Index",
      warn2: "⚠ NO REPEATS PERMITTED — PBS",
    },
    tip: "Warfarin has NO PBS repeats — each month requires a new prescription. 5 repeats written is a critical error. Always counsel about INR monitoring, alcohol, diet (vitamin K), and drug interactions. Report to prescriber immediately.",
  },
  {
    id: "case-3",
    caseNumber: 3,
    title: "Case 3 — Amoxicillin Suspension (New Patient)",
    patientLookup: {
      requiresNewPatient: true,
      expectedNewPatient: {
        surname: "HENDERSON",
        firstname: "LIAM",
        title: "MASTER",
        sex: "M",
        dateOfBirth: "12/05/2009",
        address: "7 MAPLE DRIVE",
        suburb: "NORTHCOTE",
        postcode: "3070",
        medicareCard: "5511-22233-1",
        medicareValidTo: "12/2022",
      },
      prescriptionPatient: {
        name: "LIAM HENDERSON",
        address: "7 MAPLE DRIVE, NORTHCOTE 3070",
        mcare: "MCare 5511-22233-1  to 12/2022",
      },
    },
    price: "$5.40",
    doctor: "WATSON, EMILY",
    prescriberNo: "3847291",
    date: "27/06/17",
    scriptType: "N — NHS",
    drug: "AMOXICILLIN 250MG/5ML ORAL SUSPENSION",
    correctDrugSeedId: "amoxycillin-an-susp-250",
    directions: "Give 10mL tds for 10 days",
    repeats: "0",
    qty: "300mL",
    price2: "$5.40",
    correctWarnings: [
      "Shake well before use",
      "Keep refrigerated",
      "Complete the full course",
      "Discard unused portion after 7 days",
    ],
    errors: [],
    drugDetails: {
      name: "AMOXICILLIN SUSP (G)",
      schedule: "S4",
      pbs: "NHS: 4244H",
      pbsClass: "Penicillins",
      claimable: "Claimable",
      f2t: "",
      manufacturer: "Alphapharm Pty Ltd",
      cost: "$2.10",
      retail: "$5.40",
      cmi: true,
      newDrug: false,
      warn1: "PDL: Reconstitute with water",
      warn2: "PDL: Paediatric dose weight-based",
    },
    tip: "Dose check: 40mg/kg/day for otitis media. 28kg × 40 = 1120mg/day ÷ 3 = ~373mg/dose. 10mL × 250mg/5mL = 500mg/dose — slightly high but within acceptable range. Store in fridge, shake well, discard after 7 days once reconstituted.",
  },
  {
    id: "case-4",
    caseNumber: 4,
    title: "Case 4 — Temazepam S8 (Quantity Error)",
    patientLookup: {
      requiresNewPatient: false,
      existingPatientSeedId: "patient-david-park-hawthorn",
      prescriptionPatient: {
        name: "DAVID PARK",
        address: "31 RIVERVIEW RD, HAWTHORN 3122",
        mcare: "MCare 6622-33441-1  to 09/2020",
      },
    },
    price: "Private",
    doctor: "KOWALSKI, ANNA",
    prescriberNo: "9012847",
    date: "27/06/17",
    scriptType: "P — Private",
    drug: "TEMAZEPAM TAB 10MG",
    correctDrugSeedId: "temazepam-temaze-tab-10",
    directions: "Take 1-2 tabs nocte prn",
    repeats: "0",
    qty: "50",
    price2: "Private",
    correctWarnings: [
      "May cause drowsiness",
      "Avoid alcohol",
      "Avoid driving/machinery",
      "Do not stop suddenly",
    ],
    errors: [
      "⚠ S8 DRUG: Maximum quantity 30 tablets (VIC). Script written for 50 — cannot be dispensed as written. Contact prescriber.",
      "⚠ Patient has history of alcohol dependency — discuss risks with pharmacist before dispensing.",
    ],
    drugDetails: {
      name: "TEMAZEPAM (G)",
      schedule: "S8 — CONTROLLED",
      pbs: "Private only",
      pbsClass: "Benzodiazepines — Hypnotics",
      claimable: "Not PBS Claimable",
      f2t: "S8",
      manufacturer: "Alphapharm",
      cost: "Private",
      retail: "Private",
      cmi: true,
      newDrug: false,
      warn1: "⚠ SCHEDULE 8 — S8 register required",
      warn2: "⚠ VIC Max Qty: 30 tabs (private)",
    },
    tip: "S8 drugs require entry in the S8 register. VIC maximum: 30 tablets on a private script (no repeats). 50 tablets cannot be dispensed — prescriber must rewrite. Patient's history of alcohol dependency adds risk with benzodiazepines — pharmacist counselling essential.",
  },
  {
    id: "case-5",
    caseNumber: 5,
    title: "Case 5 — Metformin + Drug Interaction",
    patientLookup: {
      requiresNewPatient: false,
      existingPatientSeedId: "patient-carol-simmons-carlton",
      prescriptionPatient: {
        name: "CAROL SIMMONS",
        address: "78 LYGON ST, CARLTON 3053",
        mcare: "MCare 7733-44552-3  to 04/2023",
      },
    },
    price: "$6.50",
    doctor: "YUEN, RICHARD",
    prescriberNo: "5512847",
    date: "27/06/17",
    scriptType: "N — NHS",
    drug: "METFORMIN TAB 1000MG",
    correctDrugSeedId: "metformin-an-tab-1000",
    directions: "Take ONE tab bd pc",
    repeats: "5",
    qty: "60",
    price2: "$6.50",
    correctWarnings: ["Take with food or milk", "Regular blood tests required"],
    errors: [
      "⚠ DRUG INTERACTION: Cimetidine inhibits renal tubular secretion of metformin — increased metformin levels. Monitor for lactic acidosis.",
      "⚠ eGFR 58 — use with caution. Metformin contraindicated if eGFR <30. Monitor renal function.",
    ],
    drugDetails: {
      name: "METFORMIN (G)",
      schedule: "S4",
      pbs: "NHS: 1162L",
      pbsClass: "Biguanides — Antidiabetics",
      claimable: "Claimable",
      f2t: "",
      manufacturer: "Sandoz",
      cost: "$2.80",
      retail: "$6.50",
      cmi: true,
      newDrug: false,
      warn1: "PDL: Monitor renal function",
      warn2: "PDL: Drug interaction — cimetidine",
    },
    tip: "Cimetidine is an organic cation and inhibits renal tubular secretion of metformin (also a cation), increasing metformin AUC by ~40%. Combined with mild CKD (eGFR 58), risk of metformin accumulation and lactic acidosis is elevated. Recommend contacting prescriber.",
  },
  {
    id: "case-6",
    caseNumber: 6,
    title: "Case 6 — Doxycycline (New Patient, Complex Counselling)",
    patientLookup: {
      requiresNewPatient: true,
      expectedNewPatient: {
        surname: "CHANG",
        firstname: "FIONA",
        title: "MS",
        sex: "F",
        dateOfBirth: "15/03/1998",
        address: "22 CHAPEL ST",
        suburb: "PRAHRAN",
        postcode: "3181",
        medicareCard: "8844-55663-2",
        medicareValidTo: "07/2024",
      },
      prescriptionPatient: {
        name: "FIONA CHANG",
        address: "22 CHAPEL ST, PRAHRAN 3181",
        mcare: "MCare 8844-55663-2  to 07/2024",
      },
    },
    price: "$13.01",
    doctor: "BRADLEY, TOM",
    prescriberNo: "6623941",
    date: "27/06/17",
    scriptType: "N — NHS",
    drug: "DOXYCYCLINE TAB 50MG",
    correctDrugSeedId: "doxycycline-an-tab-50",
    directions: "Take ONE tab bd",
    repeats: "5",
    qty: "60",
    price2: "$13.01",
    correctWarnings: [
      "Take with a full glass of water",
      "Avoid sunlight / use sunscreen",
      "Do not lie down for 30 min after taking",
      "Avoid dairy/antacids within 2 hours",
      "Complete the full course",
    ],
    errors: [],
    drugDetails: {
      name: "DOXYCYCLINE (G)",
      schedule: "S4",
      pbs: "NHS: 1678N",
      pbsClass: "Tetracyclines",
      claimable: "Claimable",
      f2t: "",
      manufacturer: "Pfizer",
      cost: "$4.50",
      retail: "$13.01",
      cmi: true,
      newDrug: false,
      warn1: "PDL: Photosensitivity — sunscreen",
      warn2: "PDL: Oesophageal ulceration risk",
    },
    tip: "Doxycycline counselling: (1) Take upright with full glass of water, remain upright 30 min — prevents oesophageal ulceration. (2) Photosensitivity — use SPF 50+ sunscreen daily. (3) Avoid dairy, antacids, iron within 2 hours. (4) Counsel on backup contraception with OCP. (5) Complete full course for acne.",
  },
];

export const ALL_WARNINGS: WarningLabel[] = [
  { lbl: "18", sig: "L18",  text: "Take with food or milk" },
  { lbl: "5",  sig: "L5",   text: "Complete the full course" },
  { lbl: "A",  sig: "SW",   text: "Shake well before use" },
  { lbl: "C",  sig: "30AC", text: "Keep refrigerated" },
  { lbl: "D",  sig: "UAF",  text: "May cause nausea" },
  { lbl: "E",  sig: "UAD",  text: "May cause drowsiness" },
  { lbl: "F",  sig: "ALC",  text: "Avoid alcohol" },
  { lbl: "G",  sig: "DRV",  text: "Avoid driving/machinery" },
  { lbl: "H",  sig: "SUN",  text: "Avoid sunlight / use sunscreen" },
  { lbl: "I",  sig: "WTR",  text: "Take with a full glass of water" },
  { lbl: "J",  sig: "DSC",  text: "Discard unused portion after 7 days" },
  { lbl: "K",  sig: "BT",   text: "Regular blood tests required" },
  { lbl: "L",  sig: "LYD",  text: "Do not lie down for 30 min after taking" },
  { lbl: "M",  sig: "DAI",  text: "Avoid dairy/antacids within 2 hours" },
  { lbl: "N",  sig: "STP",  text: "Do not stop suddenly" },
  { lbl: "O",  sig: "ASP",  text: "Do not take aspirin/NSAIDs without advice" },
];

export const ABBREVS: Record<string, string> = {
  od:    "once daily",
  bd:    "twice daily",
  tds:   "three times daily",
  qid:   "four times daily",
  mane:  "in the morning",
  nocte: "at night",
  prn:   "as needed",
  sos:   "when required",
  pc:    "after meals",
  ac:    "before meals",
  cc:    "with food",
  stat:  "immediately",
  cap:   "capsule",
  caps:  "capsules",
  tab:   "tablet",
  tabs:  "tablets",
  susp:  "suspension",
  ml:    "mL",
  mcg:   "micrograms",
  mg:    "milligrams",
};
