import type { PracticeCase, WarningLabel } from "@/lib/types/case";

export const STATIC_CASES: PracticeCase[] = [
  {
    id: "case-1",
    caseNumber: 1,
    title: "Case 1 — Erythromycin 250mg",
    patientLookup: {
      requiresNewPatient: false,
      existingPatientSeedId: "patient-john-smith-abbotsford",
      prescriptionPatient: {
        name: "JOHN SMITH",
        address: "20 TRENERRY CRESCENT, ABBOTSFORD 3067",
        mcare: "MCare 3333-00000-11  to 11/2020",
      },
    },
    price: "$13.01",
    doctor: "WILLIS, HARRY",
    prescriberNo: "8015996",
    date: "27/06/17",
    scriptType: "N — NHS",
    drug: "ERYTHROMYCIN (MAYNE PHARMA) CAP 250MG",
    correctDrugSeedId: "erythromycin-mayne-cap-250",
    directions: "Take ONE capsule tds",
    repeats: "1",
    qty: "25",
    price2: "$20.86",
    correctWarnings: ["Take with food or milk", "Complete the full course", "May cause nausea"],
    errors: [],
    expectedDecision: "dispense",
    drugDetails: {
      name: "ERYTHROMYCIN (G)",
      schedule: "S4",
      pbs: "NHS: 1404X",
      pbsClass: "Macrolides",
      claimable: "Not Claimable",
      f2t: "F2T",
      manufacturer: "Mayne Products Pty Ltd",
      cost: "$4.78",
      retail: "$15.34",
      cmi: true,
      newDrug: true,
      warn1: "PDL Warn: Similar Names",
      warn2: "PDL Warn: Caution Strengths",
    },
    tip: "Erythromycin is a macrolide antibiotic. Check the selected product information, patient allergies and interactions, and counsel the patient to complete the prescribed course. PBS quantities and repeats are item-specific and must be checked against a current reference.",
  },
  {
    id: "case-2",
    caseNumber: 2,
    title: "Case 2 — Warfarin 5mg",
    patientLookup: {
      requiresNewPatient: false,
      existingPatientSeedId: "patient-margaret-jones-fitzroy",
      prescriptionPatient: {
        name: "MARGARET JONES",
        address: "44 OAK STREET, FITZROY 3065",
        mcare: "MCare 4444-11111-22  to 06/2021",
      },
    },
    price: "$6.50",
    doctor: "CHEN, LINDA",
    prescriberNo: "7029384",
    date: "27/06/17",
    scriptType: "N — NHS",
    drug: "WARFARIN (COUMADIN) TAB 5MG",
    correctDrugSeedId: "warfarin-coumadin-tab-5",
    directions: "Take as directed",
    repeats: "2",
    qty: "50",
    price2: "$6.50",
    correctWarnings: [
      "Avoid alcohol",
      "Regular blood tests required",
      "Do not take aspirin/NSAIDs without advice",
    ],
    errors: [],
    expectedDecision: "dispense",
    drugDetails: {
      name: "WARFARIN (G)",
      schedule: "S4",
      pbs: "NHS: 1055C",
      pbsClass: "Anticoagulants",
      claimable: "Claimable",
      f2t: "",
      manufacturer: "Aspen Pharma",
      cost: "$3.20",
      retail: "$6.50",
      cmi: true,
      newDrug: false,
      warn1: "PDL Warn: Narrow Therapeutic Index",
      warn2: "PDL Warn: Confirm current INR monitoring and dose plan",
    },
    tip: "Warfarin has a narrow therapeutic index. Confirm the current dose plan and INR follow-up, check interacting medicines, and use the current PBS item listing rather than applying a blanket repeat rule.",
  },
  {
    id: "case-3",
    caseNumber: 3,
    title: "Case 3 — Amoxicillin Suspension (New Patient)",
    patientLookup: {
      requiresNewPatient: true,
      expectedNewPatient: {
        surname: "HENDERSON",
        firstname: "LIAM",
        title: "MASTER",
        sex: "M",
        dateOfBirth: "12/05/2009",
        address: "7 MAPLE DRIVE",
        suburb: "NORTHCOTE",
        postcode: "3070",
        medicareCard: "5511-22233-1",
        medicareValidTo: "12/2022",
      },
      prescriptionPatient: {
        name: "LIAM HENDERSON",
        address: "7 MAPLE DRIVE, NORTHCOTE 3070",
        mcare: "MCare 5511-22233-1  to 12/2022",
      },
    },
    price: "$5.40",
    doctor: "WATSON, EMILY",
    prescriberNo: "3847291",
    date: "27/06/17",
    scriptType: "N — NHS",
    drug: "AMOXICILLIN 250MG/5ML ORAL SUSPENSION",
    correctDrugSeedId: "amoxycillin-an-susp-250",
    directions: "Give 10mL tds for 10 days",
    repeats: "0",
    qty: "300mL",
    price2: "$5.40",
    correctWarnings: [
      "Shake well before use",
      "Keep refrigerated",
      "Complete the full course",
    ],
    errors: [],
    expectedDecision: "dispense",
    drugDetails: {
      name: "AMOXICILLIN SUSP (G)",
      schedule: "S4",
      pbs: "NHS: 4244H",
      pbsClass: "Penicillins",
      claimable: "Claimable",
      f2t: "",
      manufacturer: "Alphapharm Pty Ltd",
      cost: "$2.10",
      retail: "$5.40",
      cmi: true,
      newDrug: false,
      warn1: "PDL: Reconstitute with water",
      warn2: "PDL: Paediatric dose weight-based",
    },
    tip: "For paediatric liquids, verify the dose using the documented weight, concentration, indication and current paediatric reference. Reconstitution, storage and beyond-use instructions must come from the exact product selected and must support completion of the prescribed course.",
  },
  {
    id: "case-4",
    caseNumber: 4,
    title: "Case 4 — Temazepam 10mg",
    patientLookup: {
      requiresNewPatient: false,
      existingPatientSeedId: "patient-david-park-hawthorn",
      prescriptionPatient: {
        name: "DAVID PARK",
        address: "31 RIVERVIEW RD, HAWTHORN 3122",
        mcare: "MCare 6622-33441-1  to 09/2020",
      },
    },
    price: "Private",
    doctor: "KOWALSKI, ANNA",
    prescriberNo: "9012847",
    date: "27/06/17",
    scriptType: "P — Private",
    drug: "TEMAZEPAM TAB 10MG",
    correctDrugSeedId: "temazepam-temaze-tab-10",
    directions: "Take 1-2 tabs nocte prn",
    repeats: "0",
    qty: "50",
    price2: "Private",
    correctWarnings: [
      "May cause drowsiness",
      "Avoid alcohol",
      "Avoid driving/machinery",
      "Do not stop suddenly",
    ],
    errors: [
      "The quantity and dose range require pharmacist assessment before supply.",
      "The documented history of alcohol dependence increases sedation, dependence and misuse risk. Hold the supply and clarify the treatment plan with the prescriber.",
    ],
    expectedDecision: "hold_contact_prescriber",
    drugDetails: {
      name: "TEMAZEPAM (G)",
      schedule: "S4 — monitored in SafeScript (VIC)",
      pbs: "Private only",
      pbsClass: "Benzodiazepines — Hypnotics",
      claimable: "Not PBS Claimable",
      f2t: "",
      manufacturer: "Alphapharm",
      cost: "Private",
      retail: "Private",
      cmi: true,
      newDrug: false,
      warn1: "PDL: Sedation and dependence risk — pharmacist review",
      warn2: "PDL: SafeScript-monitored medicine in Victoria",
    },
    tip: "Temazepam is Schedule 4, not Schedule 8. In Victoria it is monitored in SafeScript. Review indication, duration, dose, quantity, other sedatives and substance-use history, then document any prescriber clarification before supply.",
  },
  {
    id: "case-5",
    caseNumber: 5,
    title: "Case 5 — Metformin 1000mg",
    patientLookup: {
      requiresNewPatient: false,
      existingPatientSeedId: "patient-carol-simmons-carlton",
      prescriptionPatient: {
        name: "CAROL SIMMONS",
        address: "78 LYGON ST, CARLTON 3053",
        mcare: "MCare 7733-44552-3  to 04/2023",
      },
    },
    price: "$6.50",
    doctor: "YUEN, RICHARD",
    prescriberNo: "5512847",
    date: "27/06/17",
    scriptType: "N — NHS",
    drug: "METFORMIN TAB 1000MG",
    correctDrugSeedId: "metformin-an-tab-1000",
    directions: "Take ONE tab bd pc",
    repeats: "5",
    qty: "60",
    price2: "$6.50",
    correctWarnings: ["Take with food or milk", "Regular blood tests required"],
    errors: [
      "⚠ DRUG INTERACTION: Cimetidine inhibits renal tubular secretion of metformin — increased metformin levels. Monitor for lactic acidosis.",
      "⚠ eGFR 58 — use with caution. Metformin contraindicated if eGFR <30. Monitor renal function.",
    ],
    expectedDecision: "hold_contact_prescriber",
    drugDetails: {
      name: "METFORMIN (G)",
      schedule: "S4",
      pbs: "NHS: 1162L",
      pbsClass: "Biguanides — Antidiabetics",
      claimable: "Claimable",
      f2t: "",
      manufacturer: "Sandoz",
      cost: "$2.80",
      retail: "$6.50",
      cmi: true,
      newDrug: false,
      warn1: "PDL: Monitor renal function",
      warn2: "PDL: Drug interaction — cimetidine",
    },
    tip: "Cimetidine is an organic cation and inhibits renal tubular secretion of metformin (also a cation), increasing metformin AUC by ~40%. Combined with mild CKD (eGFR 58), risk of metformin accumulation and lactic acidosis is elevated. Recommend contacting prescriber.",
  },
  {
    id: "case-6",
    caseNumber: 6,
    title: "Case 6 — Doxycycline (New Patient, Complex Counselling)",
    patientLookup: {
      requiresNewPatient: true,
      expectedNewPatient: {
        surname: "CHANG",
        firstname: "FIONA",
        title: "MS",
        sex: "F",
        dateOfBirth: "15/03/1998",
        address: "22 CHAPEL ST",
        suburb: "PRAHRAN",
        postcode: "3181",
        medicareCard: "8844-55663-2",
        medicareValidTo: "07/2024",
      },
      prescriptionPatient: {
        name: "FIONA CHANG",
        address: "22 CHAPEL ST, PRAHRAN 3181",
        mcare: "MCare 8844-55663-2  to 07/2024",
      },
    },
    price: "$13.01",
    doctor: "BRADLEY, TOM",
    prescriberNo: "6623941",
    date: "27/06/17",
    scriptType: "N — NHS",
    drug: "DOXYCYCLINE TAB 50MG",
    correctDrugSeedId: "doxycycline-an-tab-50",
    directions: "Take ONE tab bd",
    repeats: "5",
    qty: "60",
    price2: "$13.01",
    correctWarnings: [
      "Take with a full glass of water",
      "Avoid sunlight / use sunscreen",
      "Do not lie down for 30 min after taking",
      "Avoid dairy/antacids within 2 hours",
      "Complete the full course",
    ],
    errors: [],
    expectedDecision: "dispense",
    drugDetails: {
      name: "DOXYCYCLINE (G)",
      schedule: "S4",
      pbs: "NHS: 1678N",
      pbsClass: "Tetracyclines",
      claimable: "Claimable",
      f2t: "",
      manufacturer: "Pfizer",
      cost: "$4.50",
      retail: "$13.01",
      cmi: true,
      newDrug: false,
      warn1: "PDL: Photosensitivity — sunscreen",
      warn2: "PDL: Oesophageal ulceration risk",
    },
    tip: "Doxycycline counselling should cover administration with water while upright, separation from relevant interacting products, photosensitivity and the intended duration. Do not apply a blanket rule about backup contraception; check the patient's circumstances and a current medicines reference.",
  },
];

export const ALL_WARNINGS: WarningLabel[] = [
  { lbl: "18", sig: "L18", text: "Take with food or milk", aliases: ["take with food", "with food", "with meals", "take after food"] },
  { lbl: "5", sig: "L5", text: "Complete the full course", aliases: ["finish the full course", "finish the course", "complete course", "take until finished"] },
  { lbl: "A", sig: "SW", text: "Shake well before use", aliases: ["shake well", "shake before use"] },
  { lbl: "C", sig: "30AC", text: "Keep refrigerated", aliases: ["store in the fridge", "keep in fridge", "refrigerate"] },
  { lbl: "D", sig: "UAF", text: "May cause nausea", aliases: ["may cause stomach upset", "may make you feel sick", "can cause nausea"] },
  { lbl: "E", sig: "UAD", text: "May cause drowsiness", aliases: ["may make you drowsy", "may cause sleepiness", "can cause drowsiness"] },
  { lbl: "F", sig: "ALC", text: "Avoid alcohol", aliases: ["do not drink alcohol", "no alcohol"] },
  { lbl: "G", sig: "DRV", text: "Avoid driving/machinery", aliases: ["do not drive or operate machinery", "avoid driving", "do not drive"] },
  { lbl: "H", sig: "SUN", text: "Avoid sunlight / use sunscreen", aliases: ["avoid sun and use sunscreen", "use sunscreen", "sun sensitivity", "protect from sunlight"] },
  { lbl: "I", sig: "WTR", text: "Take with a full glass of water", aliases: ["take with plenty of water", "full glass of water"] },
  { lbl: "K", sig: "BT", text: "Regular blood tests required", aliases: ["regular blood tests", "blood test monitoring", "requires blood tests"] },
  { lbl: "L", sig: "LYD", text: "Do not lie down for 30 min after taking", aliases: ["stay upright for 30 minutes", "do not lie down for 30 minutes", "remain upright"] },
  { lbl: "M", sig: "DAI", text: "Avoid dairy/antacids within 2 hours", aliases: ["separate dairy and antacids by 2 hours", "avoid antacids within 2 hours", "separate minerals by 2 hours"] },
  { lbl: "N", sig: "STP", text: "Do not stop suddenly", aliases: ["do not stop abruptly", "dont stop suddenly", "do not suddenly stop"] },
  { lbl: "O", sig: "ASP", text: "Do not take aspirin/NSAIDs without advice", aliases: ["avoid aspirin and nsaids", "check before taking ibuprofen", "do not take ibuprofen without advice"] },
];

export const ABBREVS: Record<string, string> = {
  od:    "once daily",
  bd:    "twice daily",
  tds:   "three times daily",
  qid:   "four times daily",
  mane:  "in the morning",
  nocte: "at night",
  prn:   "as needed",
  sos:   "when required",
  pc:    "after meals",
  ac:    "before meals",
  cc:    "with food",
  stat:  "immediately",
  cap:   "capsule",
  caps:  "capsules",
  tab:   "tablet",
  tabs:  "tablets",
  susp:  "suspension",
  ml:    "mL",
  mcg:   "micrograms",
  mg:    "milligrams",
};
