import type { ConsultationQuizCase, QuizDomain } from "./types";

export const QUIZ_DOMAIN_LABELS: Record<QuizDomain, string> = {
  dose_calculation: "Dose calculation",
  dose_selection: "Dose and patient factors",
  interaction: "Interactions",
  warning_labels: "Warning labels",
  consultation: "Consultation technique",
  red_flags: "Red flags",
  clinical_action: "Clinical action",
  legal_and_prescription: "Legal and prescription checks",
};

export const CONSULTATION_QUIZ_CASES: ConsultationQuizCase[] = [
  {
    id: "paediatric-amoxicillin",
    title: "Paediatric liquid: dose, volume and handover",
    subtitle: "Calculate the prescribed exposure, reconcile the quantity and choose product-specific counselling.",
    difficulty: "Advanced",
    estimatedMinutes: 8,
    focus: ["Weight-based dose", "Liquid measurement", "Warning labels"],
    patient: {
      name: "Maya Thompson",
      dateOfBirth: "22/04/2020",
      age: "6 years",
      weight: "18 kg",
      address: "8 Wattle Avenue, Geelong VIC 3220",
      consultationNotes: [
        "Maya's father is collecting the medicine for acute otitis media.",
        "No known medicine allergies and no renal disease have been reported.",
        "The household has a 5 mL kitchen teaspoon but no oral syringe.",
      ],
    },
    prescriptions: [
      {
        id: "maya-amoxicillin",
        prescriber: "Dr Olivia Martin",
        prescriberNumber: "4538217",
        date: "16/07/2026",
        items: [
          {
            medicineProfileId: "amoxicillin",
            product: "Amoxil Forte",
            formAndStrength: "Oral liquid 250 mg/5 mL",
            directions: "Give 10 mL three times daily for 7 days",
            quantity: "210 mL",
            repeats: "0",
          },
        ],
      },
    ],
    medicineProfileIds: ["amoxicillin"],
    questions: [
      {
        id: "amox-mgkg",
        domain: "dose_calculation",
        prompt: "What total daily amoxicillin dose does the prescription provide?",
        options: [
          { id: "a", text: "27.8 mg/kg/day" },
          { id: "b", text: "55.6 mg/kg/day" },
          { id: "c", text: "83.3 mg/kg/day" },
          { id: "d", text: "166.7 mg/kg/day" },
        ],
        correctOptionId: "c",
        explanation: "Each 10 mL dose contains 500 mg. Three doses provide 1,500 mg/day; 1,500 ÷ 18 kg = 83.3 mg/kg/day.",
        referenceNote: "Compare the calculated exposure with the paediatric range, indication, severity, exact product and maximum in the medicine book.",
      },
      {
        id: "amox-volume",
        domain: "dose_calculation",
        prompt: "Which quantity reconciliation is correct?",
        options: [
          { id: "a", text: "70 mL is sufficient because there are seven treatment days." },
          { id: "b", text: "105 mL is sufficient because the dose is divided." },
          { id: "c", text: "210 mL supplies exactly 10 mL × 3 doses × 7 days." },
          { id: "d", text: "The quantity cannot be calculated from the prescription." },
        ],
        correctOptionId: "c",
        explanation: "The prescribed course uses 30 mL per day for seven days, which is 210 mL before allowing for any product-specific overfill or reconstitution requirements.",
        referenceNote: "Dose-volume calculations must use the selected concentration, not only the active ingredient name.",
      },
      {
        id: "amox-labels",
        domain: "warning_labels",
        prompt: "Which label decision best follows the reference?",
        options: [
          { id: "a", text: "Apply shake well and complete-course labels; add refrigeration only if the exact reconstituted product requires it." },
          { id: "b", text: "Always apply refrigeration to every amoxicillin liquid." },
          { id: "c", text: "Apply a swallow-whole label because amoxicillin is prescription only." },
          { id: "d", text: "No ancillary labels are needed when the directions are printed." },
        ],
        correctOptionId: "a",
        explanation: "The suspension must be shaken and the defined antibacterial course completed. Refrigeration and in-use shelf life remain exact-product questions.",
        referenceNote: "The medicine book deliberately distinguishes universal suspension advice from product-dependent storage.",
      },
      {
        id: "amox-consult",
        domain: "consultation",
        prompt: "What is the best way to finish the measurement counselling?",
        options: [
          { id: "a", text: "Tell the parent that a kitchen teaspoon is close enough for most doses." },
          { id: "b", text: "Supply an appropriate oral measure, demonstrate 10 mL, then ask the parent to show or explain how each dose will be measured." },
          { id: "c", text: "Ask, ‘Do you understand?’ and accept yes as confirmation." },
          { id: "d", text: "Avoid discussing measurement because the label already states 10 mL." },
        ],
        correctOptionId: "b",
        explanation: "An appropriate measuring device plus demonstration and teach-back tests practical understanding; a household spoon is not an accurate medicine measure.",
        referenceNote: "The consultation task is to confirm what the caregiver will actually do at home.",
        critical: true,
      },
    ],
    reviewStatus: "pharmacist_review_required",
  },
  {
    id: "warfarin-erythromycin",
    title: "Double script: anticoagulant plus antibiotic",
    subtitle: "Recognise a clinically important interaction and construct a safe consultation plan.",
    difficulty: "Expert",
    estimatedMinutes: 9,
    focus: ["Double script", "INR plan", "Bleeding safety-net"],
    patient: {
      name: "Robert Nguyen",
      dateOfBirth: "03/02/1954",
      age: "72 years",
      weight: "76 kg",
      address: "41 High Street, Preston VIC 3072",
      consultationNotes: [
        "Robert takes a variable warfarin dose from an anticoagulation clinic plan.",
        "His INR was stable last week. No extra INR test has been arranged for the antibiotic course.",
        "He reports no current bleeding, black stools or recent falls.",
      ],
    },
    prescriptions: [
      {
        id: "robert-double",
        prescriber: "Dr Sophie Williams",
        prescriberNumber: "6129048",
        date: "17/07/2026",
        items: [
          {
            medicineProfileId: "warfarin",
            product: "Coumadin",
            formAndStrength: "Tablet 5 mg",
            directions: "Take as directed by the anticoagulation clinic",
            quantity: "50",
            repeats: "2",
          },
          {
            medicineProfileId: "erythromycin",
            product: "Mayne Pharma Erythromycin",
            formAndStrength: "Enteric capsule 250 mg",
            directions: "Take one capsule four times daily for 7 days",
            quantity: "28",
            repeats: "0",
          },
        ],
      },
    ],
    medicineProfileIds: ["warfarin", "erythromycin"],
    questions: [
      {
        id: "warfarin-interaction",
        domain: "interaction",
        prompt: "What is the most important unresolved issue before supply?",
        options: [
          { id: "a", text: "The two medicines must always be taken at exactly the same time." },
          { id: "b", text: "Erythromycin may alter anticoagulant effect, so an INR and bleeding-monitoring plan must be confirmed." },
          { id: "c", text: "Warfarin becomes ineffective whenever an antibiotic is used." },
          { id: "d", text: "There is no interaction because the medicines have different purposes." },
        ],
        correctOptionId: "b",
        explanation: "Erythromycin can change warfarin response and bleeding risk. The absence of an additional monitoring plan is the unresolved safety issue.",
        referenceNote: "Use both medicine profiles: each independently flags the interaction and the need for INR follow-up.",
        critical: true,
      },
      {
        id: "warfarin-action",
        domain: "clinical_action",
        prompt: "What is the best pharmacist action?",
        options: [
          { id: "a", text: "Tell Robert to stop warfarin for seven days without contacting anyone." },
          { id: "b", text: "Supply both without discussion because his INR was stable last week." },
          { id: "c", text: "Clarify the antibiotic choice and monitoring plan with the prescriber or anticoagulation service before completing supply." },
          { id: "d", text: "Reduce the erythromycin dose by half independently." },
        ],
        correctOptionId: "c",
        explanation: "The pharmacist should not independently change either prescribed regimen. The interaction and monitoring plan require clinical clarification.",
        referenceNote: "A stable historical INR does not predict the effect of a newly introduced interacting medicine.",
        critical: true,
      },
      {
        id: "warfarin-question",
        domain: "consultation",
        prompt: "Which opening question gathers the most useful information?",
        options: [
          { id: "a", text: "‘You know how to take these, don't you?’" },
          { id: "b", text: "‘What warfarin dose are you taking from your current plan, and who is checking your INR while you use this antibiotic?’" },
          { id: "c", text: "‘Would you prefer the antibiotic in a larger box?’" },
          { id: "d", text: "‘Can you avoid all green vegetables from now on?’" },
        ],
        correctOptionId: "b",
        explanation: "The question reconciles the current variable dose and identifies responsibility for follow-up without making assumptions.",
        referenceNote: "The tablet strength is not the patient's complete warfarin regimen.",
      },
      {
        id: "warfarin-redflag",
        domain: "red_flags",
        prompt: "Which symptom requires urgent assessment rather than routine follow-up?",
        options: [
          { id: "a", text: "Mild nausea after the first antibiotic dose" },
          { id: "b", text: "A metallic taste" },
          { id: "c", text: "Black stools or bleeding that will not stop" },
          { id: "d", text: "Forgetting whether the next INR is Tuesday or Wednesday" },
        ],
        correctOptionId: "c",
        explanation: "Black stools or uncontrolled bleeding may indicate major bleeding and require urgent care.",
        referenceNote: "The medicine book separates common effects from urgent bleeding symptoms.",
        critical: true,
      },
    ],
    reviewStatus: "pharmacist_review_required",
  },
  {
    id: "older-adult-sedatives",
    title: "Double script: opioid and benzodiazepine",
    subtitle: "Assess opioid tolerance, sedative burden and the quality of the proposed handover.",
    difficulty: "Expert",
    estimatedMinutes: 9,
    focus: ["Older adult", "Respiratory depression", "Controlled medicines"],
    patient: {
      name: "Margaret Ellis",
      dateOfBirth: "11/08/1947",
      age: "78 years",
      weight: "58 kg",
      address: "19 Albert Road, Ballarat VIC 3350",
      consultationNotes: [
        "Margaret says she has never used an opioid regularly.",
        "She lives alone, drinks a glass of wine most evenings and had a fall last month.",
        "Both prescriptions were issued after a brief telehealth appointment.",
      ],
    },
    prescriptions: [
      {
        id: "margaret-sedatives",
        prescriber: "Dr Anthony Bell",
        prescriberNumber: "3801442",
        date: "17/07/2026",
        items: [
          {
            medicineProfileId: "oxycodone",
            product: "OxyContin",
            formAndStrength: "Modified-release tablet 20 mg",
            directions: "Take one tablet twice daily",
            quantity: "28",
            repeats: "0",
          },
          {
            medicineProfileId: "temazepam",
            product: "Temaze",
            formAndStrength: "Capsule 20 mg",
            directions: "Take one capsule at night when required",
            quantity: "25",
            repeats: "0",
          },
        ],
      },
    ],
    medicineProfileIds: ["oxycodone", "temazepam"],
    questions: [
      {
        id: "sedatives-risk",
        domain: "interaction",
        prompt: "Which combined risk should control the supply decision?",
        options: [
          { id: "a", text: "Reduced antibiotic absorption" },
          { id: "b", text: "Additive sedation, falls and potentially fatal respiratory depression" },
          { id: "c", text: "Loss of anticoagulant effect" },
          { id: "d", text: "Severe photosensitivity" },
        ],
        correctOptionId: "b",
        explanation: "A benzodiazepine, modified-release opioid and alcohol create a high-risk CNS-depressant combination, especially in an older opioid-naive patient with a recent fall.",
        referenceNote: "Read the interaction and older-adult dose rows for both medicines together.",
        critical: true,
      },
      {
        id: "sedatives-action",
        domain: "clinical_action",
        prompt: "What is the safest next action?",
        options: [
          { id: "a", text: "Hold the prescriptions and urgently clarify indication, opioid tolerance, starting doses and the combined sedative plan with the prescriber." },
          { id: "b", text: "Supply both and advise Margaret to take them together so she remembers them." },
          { id: "c", text: "Delete the temazepam from the prescription without contacting the prescriber." },
          { id: "d", text: "Supply half the opioid tablets and change the directions independently." },
        ],
        correctOptionId: "a",
        explanation: "The risk cannot be made safe by ad-hoc label changes. The prescriber must clarify the treatment plan before supply.",
        referenceNote: "Clinical action comes before routine counselling when the intended regimen is potentially unsafe.",
        critical: true,
      },
      {
        id: "sedatives-labels",
        domain: "warning_labels",
        prompt: "If a clinically revised regimen is later supplied, which shared messages are essential?",
        options: [
          { id: "a", text: "Avoid alcohol; expect possible drowsiness; do not drive if impaired; keep the opioid secured." },
          { id: "b", text: "Take both with dairy and avoid sunlight." },
          { id: "c", text: "Crush the OxyContin tablet if it is difficult to swallow." },
          { id: "d", text: "Stop both suddenly once sleep improves." },
        ],
        correctOptionId: "a",
        explanation: "Sedation, alcohol, driving and secure storage are central. Modified-release oxycodone must be swallowed whole, not crushed.",
        referenceNote: "Labels support—but do not replace—the prior clinical safety decision.",
      },
      {
        id: "sedatives-emergency",
        domain: "red_flags",
        prompt: "Which teach-back response shows the patient understands the emergency plan?",
        options: [
          { id: "a", text: "‘If I am very sleepy, I will take another capsule to sleep it off.’" },
          { id: "b", text: "‘If my breathing becomes slow or I cannot be woken, someone should call triple zero immediately.’" },
          { id: "c", text: "‘Blue lips are a common effect that can wait until my next appointment.’" },
          { id: "d", text: "‘Alcohol will counteract the drowsiness.’" },
        ],
        correctOptionId: "b",
        explanation: "Slow breathing, blue lips, collapse or inability to wake are opioid emergencies.",
        referenceNote: "A strong consultation verifies the response the patient or carer will take, not just symptom recall.",
        critical: true,
      },
    ],
    reviewStatus: "pharmacist_review_required",
  },
  {
    id: "methotrexate-antibiotic",
    title: "Double script: weekly medicine written daily",
    subtitle: "Detect a fatal frequency error and a second interaction before discussing routine counselling.",
    difficulty: "Expert",
    estimatedMinutes: 8,
    focus: ["Weekly dosing", "Penicillin interaction", "Prescriber call"],
    patient: {
      name: "Helen Park",
      dateOfBirth: "07/06/1963",
      age: "63 years",
      weight: "64 kg",
      address: "5 Lygon Lane, Carlton VIC 3053",
      consultationNotes: [
        "Helen uses methotrexate for rheumatoid arthritis and says her usual day is Monday.",
        "She has been prescribed amoxicillin for a dental infection.",
        "Her latest renal results are not visible and she reports new mouth soreness.",
      ],
    },
    prescriptions: [
      {
        id: "helen-methotrexate",
        prescriber: "Dr Ellen Murphy",
        prescriberNumber: "3481752",
        date: "16/07/2026",
        items: [
          {
            medicineProfileId: "methotrexate",
            product: "Methotrexate Cipla",
            formAndStrength: "Tablet 10 mg",
            directions: "Take one tablet daily",
            quantity: "12",
            repeats: "2",
          },
          {
            medicineProfileId: "amoxicillin",
            product: "Amoxil",
            formAndStrength: "Capsule 500 mg",
            directions: "Take one capsule three times daily for 5 days",
            quantity: "15",
            repeats: "0",
          },
        ],
      },
    ],
    medicineProfileIds: ["methotrexate", "amoxicillin"],
    questions: [
      {
        id: "mtx-error",
        domain: "dose_selection",
        prompt: "What is the first critical error?",
        options: [
          { id: "a", text: "Methotrexate for rheumatoid arthritis is normally weekly, and daily dosing can be fatal." },
          { id: "b", text: "Methotrexate must always be taken four times daily." },
          { id: "c", text: "The quantity is too small for a daily medicine, so it is automatically safe." },
          { id: "d", text: "Monday is not an acceptable weekly dosing day." },
        ],
        correctOptionId: "a",
        explanation: "The written daily frequency conflicts with the patient's established weekly regimen and the medicine reference. This is a critical prescribing error.",
        referenceNote: "The weekly day should be explicit after lawful clarification; quantity alone cannot correct unsafe directions.",
        critical: true,
      },
      {
        id: "mtx-interaction",
        domain: "interaction",
        prompt: "What additional concern must be included in the prescriber discussion?",
        options: [
          { id: "a", text: "Amoxicillin can affect methotrexate clearance and toxicity risk, especially when renal status or toxicity symptoms are uncertain." },
          { id: "b", text: "Amoxicillin permanently stops methotrexate working." },
          { id: "c", text: "The medicines interact only if swallowed at the same minute." },
          { id: "d", text: "There are no clinically relevant issues with penicillins and methotrexate." },
        ],
        correctOptionId: "a",
        explanation: "Penicillins can increase methotrexate exposure. New mouth soreness and missing renal information raise the level of concern.",
        referenceNote: "The interaction table says to assess dose, renal function and monitoring, then contact the prescriber if unresolved.",
        critical: true,
      },
      {
        id: "mtx-action",
        domain: "clinical_action",
        prompt: "Which response is appropriate now?",
        options: [
          { id: "a", text: "Change ‘daily’ to ‘weekly’ yourself and supply both medicines." },
          { id: "b", text: "Hold supply, contact the prescriber, verify the intended methotrexate regimen and assess the mouth soreness, renal status and antibiotic plan." },
          { id: "c", text: "Supply the antibiotic but tell Helen never to take methotrexate again." },
          { id: "d", text: "Ask Helen to choose whichever directions sound familiar." },
        ],
        correctOptionId: "b",
        explanation: "Both the frequency error and potential toxicity/interaction require prescriber clarification and patient assessment before supply.",
        referenceNote: "The quiz expects a safe professional action, not an unauthorised prescription edit.",
        critical: true,
      },
      {
        id: "mtx-redflag",
        domain: "red_flags",
        prompt: "Why is the reported mouth soreness important?",
        options: [
          { id: "a", text: "It proves the dental infection has resolved." },
          { id: "b", text: "Mouth ulcers or severe soreness can be a methotrexate toxicity warning and need prompt assessment." },
          { id: "c", text: "It means the weekly dose should automatically be doubled." },
          { id: "d", text: "It is relevant only after several years of treatment." },
        ],
        correctOptionId: "b",
        explanation: "Mouth ulcers or severe mouth soreness appear in the urgent-care section because they may signal clinically important toxicity.",
        referenceNote: "Consultation details can transform an apparent clerical error into an urgent clinical problem.",
        critical: true,
      },
    ],
    reviewStatus: "pharmacist_review_required",
  },
  {
    id: "opioid-naive-fentanyl",
    title: "New fentanyl patch in an opioid-naive patient",
    subtitle: "Use opioid history, formulation and heat exposure to distinguish a routine handover from a critical hold.",
    difficulty: "Expert",
    estimatedMinutes: 8,
    focus: ["Opioid tolerance", "Patch safety", "Heat exposure"],
    patient: {
      name: "David Cohen",
      dateOfBirth: "18/10/1957",
      age: "68 years",
      weight: "81 kg",
      address: "74 Bay Road, Sandringham VIC 3191",
      consultationNotes: [
        "David has used only occasional paracetamol and codeine after surgery; he is not taking a regular opioid.",
        "He uses a heated wheat pack on his back every evening.",
        "He also presents a repeat temazepam prescription and lives with two young grandchildren.",
      ],
    },
    prescriptions: [
      {
        id: "david-fentanyl",
        prescriber: "Dr Elliot Reed",
        prescriberNumber: "7399488",
        date: "17/07/2026",
        items: [
          {
            medicineProfileId: "fentanyl",
            product: "Durogesic",
            formAndStrength: "Transdermal patch 25 micrograms/hour",
            directions: "Apply one patch every 72 hours",
            quantity: "5",
            repeats: "0",
          },
          {
            medicineProfileId: "temazepam",
            product: "Temaze",
            formAndStrength: "Capsule 10 mg",
            directions: "Take one capsule at night when required",
            quantity: "25",
            repeats: "1",
          },
        ],
      },
    ],
    medicineProfileIds: ["fentanyl", "temazepam"],
    questions: [
      {
        id: "fentanyl-tolerance",
        domain: "dose_selection",
        prompt: "Which fact makes the fentanyl prescription unsafe to treat as a routine new supply?",
        options: [
          { id: "a", text: "David is over 65 years old." },
          { id: "b", text: "He is opioid-naive; a 25 microgram/hour patch should not be initiated in an opioid-naive patient." },
          { id: "c", text: "The patch is changed every 72 hours." },
          { id: "d", text: "The quantity is five patches." },
        ],
        correctOptionId: "b",
        explanation: "The fentanyl dose guide specifically says not to initiate this patch in an opioid-naive patient because fatal respiratory depression can occur.",
        referenceNote: "Age adds vulnerability, but opioid tolerance is the decisive contraindicating history in this scenario.",
        critical: true,
      },
      {
        id: "fentanyl-action",
        domain: "clinical_action",
        prompt: "What should happen before either medicine is handed over?",
        options: [
          { id: "a", text: "Hold and contact the prescriber to verify opioid history, intended analgesic plan and concurrent sedative use." },
          { id: "b", text: "Cut the patch in half to create a lower starting dose." },
          { id: "c", text: "Supply both and ask David to try the patch for one night." },
          { id: "d", text: "Apply the first patch in the pharmacy and send him home." },
        ],
        correctOptionId: "a",
        explanation: "The regimen needs urgent clinical clarification. Patches must not be cut, and a trial dose does not remove the respiratory risk.",
        referenceNote: "The safest consultation can be a clear explanation that supply is paused while the pharmacist resolves a serious risk.",
        critical: true,
      },
      {
        id: "fentanyl-heat",
        domain: "interaction",
        prompt: "Why must the heated wheat pack be discussed?",
        options: [
          { id: "a", text: "Heat can accelerate fentanyl absorption and increase overdose risk." },
          { id: "b", text: "Heat always makes the adhesive fail without changing absorption." },
          { id: "c", text: "The patch works only when a heat pack is applied over it." },
          { id: "d", text: "Heat converts fentanyl into an antibiotic." },
        ],
        correctOptionId: "a",
        explanation: "External heat and significant fever can increase transdermal fentanyl absorption. Heat over or near the patch must be avoided.",
        referenceNote: "The medicine book treats heat as both an interaction and an ancillary-label requirement.",
        critical: true,
      },
      {
        id: "fentanyl-disposal",
        domain: "consultation",
        prompt: "If a safe revised plan later includes a patch, which teach-back is best?",
        options: [
          { id: "a", text: "‘I can leave used patches on the bedside table because the medicine has been used up.’" },
          { id: "b", text: "‘I will remove the old patch before a new one, avoid heat, and keep used and unused patches secured away from children.’" },
          { id: "c", text: "‘I will cut patches to adjust the dose when pain is better.’" },
          { id: "d", text: "‘I can add a second patch if the first has not worked after an hour.’" },
        ],
        correctOptionId: "b",
        explanation: "Used patches retain fentanyl. Preventing dose stacking, heat exposure and accidental child contact are essential practical checks.",
        referenceNote: "Teach-back should reproduce the complete safe patch-change routine.",
      },
    ],
    reviewStatus: "pharmacist_review_required",
  },
  {
    id: "apixaban-dose-reduction",
    title: "Apixaban: indication-specific dose selection",
    subtitle: "Apply age, weight, creatinine and NSAID history without borrowing rules from another indication.",
    difficulty: "Expert",
    estimatedMinutes: 8,
    focus: ["Age/weight/creatinine", "Atrial fibrillation", "Bleeding"],
    patient: {
      name: "Evelyn Scott",
      dateOfBirth: "02/12/1942",
      age: "83 years",
      weight: "54 kg",
      address: "55 Burke Road, Camberwell VIC 3124",
      consultationNotes: [
        "Indication: non-valvular atrial fibrillation.",
        "Most recent serum creatinine: 168 micromol/L.",
        "Evelyn takes naproxen most days for knee pain and noticed dark stools yesterday.",
      ],
    },
    prescriptions: [
      {
        id: "evelyn-apixaban",
        prescriber: "Dr Jonathan Lee",
        prescriberNumber: "5294061",
        date: "17/07/2026",
        items: [
          {
            medicineProfileId: "apixaban",
            product: "Eliquis",
            formAndStrength: "Tablet 5 mg",
            directions: "Take one tablet twice daily",
            quantity: "60",
            repeats: "5",
          },
        ],
      },
    ],
    medicineProfileIds: ["apixaban"],
    questions: [
      {
        id: "apixaban-criteria",
        domain: "dose_selection",
        prompt: "How many atrial-fibrillation dose-reduction criteria does Evelyn meet in the medicine book?",
        options: [
          { id: "a", text: "None" },
          { id: "b", text: "One" },
          { id: "c", text: "Two" },
          { id: "d", text: "Three" },
        ],
        correctOptionId: "d",
        explanation: "She is at least 80 years old, weighs no more than 60 kg and has serum creatinine at least 133 micromol/L: all three criteria apply.",
        referenceNote: "For non-valvular atrial fibrillation, a reduced dose is used when at least two criteria apply.",
        critical: true,
      },
      {
        id: "apixaban-rule",
        domain: "dose_selection",
        prompt: "Which interpretation is correct?",
        options: [
          { id: "a", text: "The 5 mg twice-daily prescription needs review against the 2.5 mg twice-daily AF rule and current renal guidance." },
          { id: "b", text: "Every patient over 80 must stop apixaban." },
          { id: "c", text: "The AF criteria should be applied unchanged to every DVT and surgical indication." },
          { id: "d", text: "Weight and creatinine do not matter once age is known." },
        ],
        correctOptionId: "a",
        explanation: "The reference rule is indication-specific. Evelyn meets the AF reduction criteria, so the prescribed dose requires prescriber review.",
        referenceNote: "Do not transfer a dose rule between atrial fibrillation, acute VTE, extended prevention and postoperative prophylaxis.",
        critical: true,
      },
      {
        id: "apixaban-dark-stools",
        domain: "red_flags",
        prompt: "What does the report of dark stools change?",
        options: [
          { id: "a", text: "Nothing; dark stools are an expected harmless effect." },
          { id: "b", text: "It is a possible major bleeding symptom requiring urgent assessment now." },
          { id: "c", text: "It proves the apixaban dose is too low." },
          { id: "d", text: "It matters only if Evelyn also has nausea." },
        ],
        correctOptionId: "b",
        explanation: "Black or dark tarry stools may represent gastrointestinal bleeding and are listed as an urgent-care symptom.",
        referenceNote: "The patient report takes priority over completing a routine repeat supply.",
        critical: true,
      },
      {
        id: "apixaban-nsaid",
        domain: "interaction",
        prompt: "Which statement about naproxen is most appropriate?",
        options: [
          { id: "a", text: "Regular NSAID use can increase bleeding risk and must be reviewed, particularly with current bleeding symptoms." },
          { id: "b", text: "Naproxen protects against apixaban-related bleeding." },
          { id: "c", text: "Only aspirin interacts with anticoagulants." },
          { id: "d", text: "Taking the products two hours apart removes the bleeding risk." },
        ],
        correctOptionId: "a",
        explanation: "NSAIDs add bleeding risk. Timing separation does not remove the pharmacodynamic interaction.",
        referenceNote: "The warning label and interaction table both support active medication reconciliation.",
      },
    ],
    reviewStatus: "pharmacist_review_required",
  },
  {
    id: "renal-diabetes-sick-day",
    title: "Double script: renal dosing during acute illness",
    subtitle: "Combine formulation, renal function and sick-day information across two diabetes medicines.",
    difficulty: "Expert",
    estimatedMinutes: 9,
    focus: ["Renal impairment", "Acute illness", "Therapeutic duplication"],
    patient: {
      name: "Christopher Carruthers",
      dateOfBirth: "08/01/1978",
      age: "48 years",
      weight: "92 kg",
      address: "173 Oakendon Street, Adelaide SA 5000",
      consultationNotes: [
        "Latest eGFR is 28 mL/min/1.73 m².",
        "Christopher has had vomiting and poor fluid intake for two days.",
        "His medication bag also contains Janumet, but he is unsure whether he still takes it.",
      ],
    },
    prescriptions: [
      {
        id: "christopher-diabetes",
        prescriber: "Dr Elliot Reed",
        prescriberNumber: "7399488",
        date: "17/07/2026",
        items: [
          {
            medicineProfileId: "metformin",
            product: "Metex XR",
            formAndStrength: "Extended-release tablet 500 mg",
            directions: "Take four tablets daily with the evening meal",
            quantity: "120",
            repeats: "5",
          },
          {
            medicineProfileId: "sitagliptin",
            product: "Januvia",
            formAndStrength: "Tablet 100 mg",
            directions: "Take one tablet daily",
            quantity: "28",
            repeats: "5",
            authority: "Streamlined 7541",
          },
        ],
      },
    ],
    medicineProfileIds: ["metformin", "sitagliptin"],
    questions: [
      {
        id: "diabetes-renal",
        domain: "dose_selection",
        prompt: "Which issue applies to both prescribed medicines?",
        options: [
          { id: "a", text: "Both doses should be accepted without renal review because the patient is under 65." },
          { id: "b", text: "Renal function materially affects safe use; the current doses require exact-product and prescriber review." },
          { id: "c", text: "Renal function matters only for injectable medicines." },
          { id: "d", text: "The dose can be selected from weight alone." },
        ],
        correctOptionId: "b",
        explanation: "Metformin safety and sitagliptin dose selection both depend on renal function. The reference does not support ignoring an eGFR of 28.",
        referenceNote: "Age is not a substitute for organ-function assessment.",
        critical: true,
      },
      {
        id: "diabetes-illness",
        domain: "clinical_action",
        prompt: "How should the vomiting and poor fluid intake affect the consultation?",
        options: [
          { id: "a", text: "Treat them as irrelevant because they started after the prescription was written." },
          { id: "b", text: "Pause routine handover and obtain prompt clinical advice about acute illness, dehydration, renal status and the medication plan." },
          { id: "c", text: "Recommend taking all four metformin tablets without food." },
          { id: "d", text: "Double the sitagliptin until the patient is eating normally." },
        ],
        correctOptionId: "b",
        explanation: "Acute vomiting and dehydration can increase metformin-related risk and may worsen renal function. This is a sick-day escalation, not routine counselling.",
        referenceNote: "The medicine book flags persistent vomiting or severe dehydration for urgent advice.",
        critical: true,
      },
      {
        id: "diabetes-duplication",
        domain: "interaction",
        prompt: "Why must the Janumet box be reconciled before supply?",
        options: [
          { id: "a", text: "Janumet may already contain sitagliptin and metformin, creating therapeutic duplication." },
          { id: "b", text: "Janumet is another name for insulin." },
          { id: "c", text: "Owning an old medicine box always means the patient is allergic to it." },
          { id: "d", text: "It changes the patient's date of birth." },
        ],
        correctOptionId: "a",
        explanation: "Combination products can hide duplicate active ingredients. The current medication list must be confirmed before separate metformin and sitagliptin are supplied.",
        referenceNote: "The sitagliptin profile explicitly names fixed-dose combinations as a duplication risk.",
        critical: true,
      },
      {
        id: "diabetes-formulation",
        domain: "warning_labels",
        prompt: "If a safe revised plan later includes Metex XR, which instruction is formulation-specific?",
        options: [
          { id: "a", text: "Crush the tablets and mix them with water." },
          { id: "b", text: "Swallow the extended-release tablets whole and take metformin with food." },
          { id: "c", text: "Take the entire dose only during fasting." },
          { id: "d", text: "Use the extended-release tablets as if they were immediate-release." },
        ],
        correctOptionId: "b",
        explanation: "The extended-release matrix must be swallowed whole, and taking metformin with food can reduce gastrointestinal intolerance.",
        referenceNote: "Formulation is part of the medicine identity; XR and immediate-release instructions are not interchangeable.",
      },
    ],
    reviewStatus: "pharmacist_review_required",
  },
  {
    id: "doxycycline-adolescent",
    title: "Adolescent acne: administration and hidden products",
    subtitle: "Distinguish long-term acne counselling from an acute antibiotic-course script.",
    difficulty: "Advanced",
    estimatedMinutes: 7,
    focus: ["Adolescent", "Mineral interactions", "Oesophageal injury"],
    patient: {
      name: "Sienna Brooks",
      dateOfBirth: "29/11/2009",
      age: "16 years",
      weight: "52 kg",
      address: "63 Bell Street, Coburg VIC 3058",
      consultationNotes: [
        "The dermatologist prescribed doxycycline for acne.",
        "Sienna takes an iron tablet and a multivitamin at breakfast and uses an antacid most nights.",
        "She usually takes tablets immediately before lying down and plays outdoor sport.",
      ],
    },
    prescriptions: [
      {
        id: "sienna-doxycycline",
        prescriber: "Dr Nisha Rao",
        prescriberNumber: "7812456",
        date: "15/07/2026",
        items: [
          {
            medicineProfileId: "doxycycline",
            product: "Doxycycline Sandoz",
            formAndStrength: "Tablet 100 mg",
            directions: "Take one tablet daily",
            quantity: "30",
            repeats: "2",
          },
        ],
      },
    ],
    medicineProfileIds: ["doxycycline"],
    questions: [
      {
        id: "doxy-products",
        domain: "interaction",
        prompt: "Which products are most likely to reduce doxycycline absorption?",
        options: [
          { id: "a", text: "Iron, mineral-containing multivitamins and antacids" },
          { id: "b", text: "Plain water and sunscreen" },
          { id: "c", text: "A non-medicated lip balm" },
          { id: "d", text: "An oral measuring syringe" },
        ],
        correctOptionId: "a",
        explanation: "Iron, calcium, magnesium, aluminium and zinc can bind doxycycline and reduce absorption. Exact separation advice should follow the selected product information.",
        referenceNote: "A useful consultation asks about supplements and antacids, not only prescribed medicines.",
      },
      {
        id: "doxy-administration",
        domain: "consultation",
        prompt: "Which administration explanation is best?",
        options: [
          { id: "a", text: "Take it dry immediately before bed." },
          { id: "b", text: "Take it with a full glass of water and remain upright for at least 30 minutes." },
          { id: "c", text: "Crush it and lie flat to improve absorption." },
          { id: "d", text: "Take two tablets whenever one dose is late." },
        ],
        correctOptionId: "b",
        explanation: "Water and remaining upright reduce oesophageal irritation and ulceration.",
        referenceNote: "The patient's current bedtime habit makes this a practical, patient-specific counselling priority.",
        critical: true,
      },
      {
        id: "doxy-course-label",
        domain: "warning_labels",
        prompt: "Should the ‘complete the full course’ label be applied automatically?",
        options: [
          { id: "a", text: "Yes, to every doxycycline supply regardless of indication." },
          { id: "b", text: "No. It applies to a defined antibacterial course, not automatically to every long-term acne regimen." },
          { id: "c", text: "No warning labels can be used for acne." },
          { id: "d", text: "Only if Sienna is under 18." },
        ],
        correctOptionId: "b",
        explanation: "Course-completion language should reflect the intended regimen. Long-term acne therapy is not handled as a fixed seven-day infection course.",
        referenceNote: "Warning labels are selected from indication and formulation, not only the generic medicine name.",
      },
      {
        id: "doxy-safety",
        domain: "red_flags",
        prompt: "Which new symptom after a dose needs prompt assessment?",
        options: [
          { id: "a", text: "Painful swallowing or severe chest pain" },
          { id: "b", text: "Mild dislike of the tablet colour" },
          { id: "c", text: "Wanting to play sport in the afternoon" },
          { id: "d", text: "Needing a glass of water" },
        ],
        correctOptionId: "a",
        explanation: "Painful swallowing or severe chest pain may indicate oesophageal injury and should not be dismissed as routine indigestion.",
        referenceNote: "Sun protection is also required, but it does not replace safety-netting for oesophageal symptoms.",
        critical: true,
      },
    ],
    reviewStatus: "pharmacist_review_required",
  },
  {
    id: "lithium-acute-illness",
    title: "Lithium: acute illness and an OTC interaction",
    subtitle: "Recognise toxicity risk from dehydration and self-selected ibuprofen.",
    difficulty: "Expert",
    estimatedMinutes: 8,
    focus: ["Narrow therapeutic index", "NSAID", "Sick-day escalation"],
    patient: {
      name: "Rahul Mehta",
      dateOfBirth: "29/01/1982",
      age: "44 years",
      weight: "74 kg",
      address: "14 Paisley Street, Footscray VIC 3011",
      consultationNotes: [
        "Rahul has had vomiting and diarrhoea with reduced fluid intake for two days.",
        "He started ibuprofen 400 mg three times daily yesterday for fever and aches.",
        "His usual fine tremor is now coarse, and his partner says he is walking unsteadily.",
      ],
    },
    prescriptions: [
      {
        id: "rahul-lithium",
        prescriber: "Dr Ellen Murphy",
        prescriberNumber: "3481752",
        date: "17/07/2026",
        items: [
          {
            medicineProfileId: "lithium",
            product: "Quilonum SR",
            formAndStrength: "Sustained-release tablet 450 mg",
            directions: "Take one tablet twice daily",
            quantity: "100",
            repeats: "2",
          },
        ],
      },
    ],
    medicineProfileIds: ["lithium"],
    questions: [
      {
        id: "lithium-mechanism",
        domain: "interaction",
        prompt: "Which combination most strongly explains the increased toxicity risk?",
        options: [
          { id: "a", text: "Dehydration plus an NSAID can reduce lithium clearance and raise its concentration." },
          { id: "b", text: "A stable salt intake always makes lithium ineffective." },
          { id: "c", text: "Ibuprofen lowers lithium to a subtherapeutic concentration." },
          { id: "d", text: "Vomiting increases lithium clearance enough to prevent toxicity." },
        ],
        correctOptionId: "a",
        explanation: "Dehydration and NSAIDs can both promote lithium retention, making a previously stable dose toxic.",
        referenceNote: "OTC medicine history and current hydration are essential parts of every lithium consultation.",
        critical: true,
      },
      {
        id: "lithium-symptoms",
        domain: "red_flags",
        prompt: "Which findings are most concerning for lithium toxicity?",
        options: [
          { id: "a", text: "Coarse tremor and unsteady walking" },
          { id: "b", text: "A stable mild thirst with no other change" },
          { id: "c", text: "Wanting to drink water after exercise" },
          { id: "d", text: "A preference for salty food" },
        ],
        correctOptionId: "a",
        explanation: "A worsening or coarse tremor and ataxia/unsteady walking are urgent toxicity symptoms.",
        referenceNote: "The task is to distinguish changed neurological signs from familiar mild effects.",
        critical: true,
      },
      {
        id: "lithium-action",
        domain: "clinical_action",
        prompt: "What is the best immediate response?",
        options: [
          { id: "a", text: "Complete the routine repeat supply and suggest another ibuprofen dose." },
          { id: "b", text: "Arrange urgent clinical assessment and lithium/renal review; do not treat this as a routine handover." },
          { id: "c", text: "Tell Rahul to permanently stop lithium without assessment." },
          { id: "d", text: "Advise a sudden low-salt diet." },
        ],
        correctOptionId: "b",
        explanation: "The symptom cluster and interacting factors require urgent assessment. The pharmacist should follow the local emergency/escalation pathway.",
        referenceNote: "Routine adherence counselling comes after immediate toxicity risk is addressed.",
        critical: true,
      },
      {
        id: "lithium-longterm",
        domain: "consultation",
        prompt: "Which future counselling message is accurate after the acute episode is managed?",
        options: [
          { id: "a", text: "Maintain a reasonably consistent fluid and salt intake, avoid self-starting NSAIDs and follow the documented sick-day plan." },
          { id: "b", text: "Change fluid and salt intake dramatically whenever the weather changes." },
          { id: "c", text: "Blood tests are optional once the dose has been stable for a month." },
          { id: "d", text: "Crush Quilonum SR to make it work faster." },
        ],
        correctOptionId: "a",
        explanation: "Stable intake, interaction awareness, blood monitoring and an acute-illness plan reduce preventable lithium toxicity.",
        referenceNote: "Sustained-release tablets should also be swallowed whole.",
      },
    ],
    reviewStatus: "pharmacist_review_required",
  },
  {
    id: "dexamfetamine-authentication",
    title: "Schedule 8: dose, authority and prescriber identity",
    subtitle: "Separate an age-appropriate dose from an unauthenticated prescription.",
    difficulty: "Expert",
    estimatedMinutes: 9,
    focus: ["Adolescent dosing", "Authority", "Prescription authentication"],
    patient: {
      name: "Noah Wilson",
      dateOfBirth: "12/05/2012",
      age: "14 years",
      weight: "48 kg",
      address: "6 Sydney Road, Brunswick VIC 3056",
      consultationNotes: [
        "Noah's parent says this is continuation ADHD treatment and the usual dose is 5 mg morning and noon.",
        "The printed prescriber is Dr Nisha Rao, but the number on the script is 9911002. The verified directory number for Dr Rao is 7812456.",
        "The prescription shows streamlined authority code 1912 and the parent asks whether a decongestant is safe for a cold.",
      ],
    },
    prescriptions: [
      {
        id: "noah-dexamfetamine",
        prescriber: "Dr Nisha Rao",
        prescriberNumber: "9911002",
        date: "16/07/2026",
        items: [
          {
            medicineProfileId: "dexamfetamine",
            product: "Aspen Dexamfetamine",
            formAndStrength: "Tablet 5 mg",
            directions: "Take one tablet in the morning and one at noon",
            quantity: "100",
            repeats: "0",
            authority: "Streamlined 1912",
          },
        ],
        annotations: ["Schedule 8 prescription", "Continuation ADHD treatment"],
      },
    ],
    medicineProfileIds: ["dexamfetamine"],
    questions: [
      {
        id: "dex-dose",
        domain: "dose_selection",
        prompt: "What does the medicine-book dose guide say about the written dose for a 14-year-old?",
        options: [
          { id: "a", text: "A 5 mg once- or twice-daily starting regimen is within the common guide for children at least 6 years, but individual monitoring still applies." },
          { id: "b", text: "Any dexamfetamine dose is prohibited under age 18." },
          { id: "c", text: "The usual adolescent starting dose is 60 mg twice daily." },
          { id: "d", text: "Age, indication and monitoring are irrelevant for psychostimulants." },
        ],
        correctOptionId: "a",
        explanation: "The written dose is not inherently outside the common age guide. That does not resolve the prescription-authentication problem.",
        referenceNote: "A clinically plausible dose can still appear on an invalid or suspicious prescription.",
      },
      {
        id: "dex-number",
        domain: "legal_and_prescription",
        prompt: "What is the critical prescription problem?",
        options: [
          { id: "a", text: "The streamlined code has four digits." },
          { id: "b", text: "The printed prescriber number does not match the independently verified directory number." },
          { id: "c", text: "The patient is accompanied by a parent." },
          { id: "d", text: "The directions include a morning dose." },
        ],
        correctOptionId: "b",
        explanation: "The identity mismatch means the Schedule 8 prescription cannot be treated as authenticated, even though other details look plausible.",
        referenceNote: "Prescription validity and clinical appropriateness are separate checks; both must pass.",
        critical: true,
      },
      {
        id: "dex-call",
        domain: "clinical_action",
        prompt: "Which response is safest?",
        options: [
          { id: "a", text: "Supply because the parent recognises the doctor's name." },
          { id: "b", text: "Hold supply and contact the purported prescriber using independently verified directory details; document the authentication outcome." },
          { id: "c", text: "Call only a handwritten number on the script and accept any answer." },
          { id: "d", text: "Replace the prescriber number in the dispensing record without making contact." },
        ],
        correctOptionId: "b",
        explanation: "A suspicious controlled-drug prescription should be authenticated through trusted contact details before any supply decision.",
        referenceNote: "The authority code does not cure an identity mismatch.",
        critical: true,
      },
      {
        id: "dex-decongestant",
        domain: "interaction",
        prompt: "How should the decongestant question be handled?",
        options: [
          { id: "a", text: "Recommend any stimulant decongestant because it will balance dexamfetamine." },
          { id: "b", text: "Check the exact product: sympathomimetic decongestants can add cardiovascular and CNS effects, so avoid casual blanket reassurance." },
          { id: "c", text: "Say that non-prescription products never interact with Schedule 8 medicines." },
          { id: "d", text: "Tell the parent to double the dexamfetamine during the cold." },
        ],
        correctOptionId: "b",
        explanation: "Some decongestants are sympathomimetics and may increase cardiovascular or CNS effects. The exact product and patient factors must be checked.",
        referenceNote: "OTC-product questions are an assessed part of medication reconciliation and counselling.",
      },
    ],
    reviewStatus: "pharmacist_review_required",
  },
];

export function findConsultationQuizCase(id: string): ConsultationQuizCase | null {
  return CONSULTATION_QUIZ_CASES.find((quizCase) => quizCase.id === id) ?? null;
}
