/**
 * How students actually say things at the counter: realistic single-message
 * wordings for every conversation topic, written from how people talk rather
 * than from the matching rules (casual, reordered, shorthand, the odd typo).
 *
 * `says` lines each make the topic's point completely — including any fact
 * the topic requires, such as the exact dose — so each should be understood.
 * `mustNot` lines are near-misses that must never earn the topic: a wrong
 * dose, negated or unsafe advice, or asking instead of telling.
 *
 * understanding.test.ts measures the conversation engine against this bank,
 * and the nearest-wording matcher (nearest.ts) uses the `says` lines as its
 * examples. How to grow it: write a fresh round of wordings in
 * phrasings-held-out.ts, measure (it is never tuned on while unseen), fix the
 * engine for what it misses — general causes first, coverage.ts for the rest —
 * then move that round's lines in here. Real student wording captured in the
 * admin portal's "Unrecognised wording" list belongs here too.
 */
export interface PhrasingBank {
  says: Record<string, string[]>;
  mustNot?: Record<string, string[]>;
}

/** Topics every case shares (the introduction, history questions and closing). */
export const SHARED_PHRASINGS: PhrasingBank = {
  says: {
    introduction: [
      "Hi, I'm Sam, one of the pharmacists here.",
      "Hello, my name is Priya and I'm the pharmacist today.",
      "Hi there, I'm the pharmacist — I'll just go through your medicine with you.",
      "Good morning, I'm Tom from the pharmacy team.",
      "Hey, I'm Jess, a pharmacist here. Have you got a few minutes to go over this?",
      "Hi, I'm a student pharmacist and I'll be looking after you today.",
      "Hello, I'm one of the pharmacists and I just need to run through a few things.",
      "G'day, I'm Alex, the pharmacist on today.",
      "Hiya, my name's Chloe and I'm working as the pharmacist today, is now a good time to chat about your meds?",
      "Morning! I'm Raj, I'm the pharmacist here, I'll just take you through this.",
      "hi im the pharmacist, ill go over this with you",
      "Good afternoon, my name is Daniel, I am one of the pharmacists on duty.",
      "Hello there, I am pharmacist in this pharmacy, I will explain your medicine.",
      "Hey mate, I'm Liam, one of the pharmacists, just gonna run through a couple things with you.",
    ],
    confirm_identity: [
      "Can I get your full name please?",
      "What's your name?",
      "Who is the prescription for?",
      "Can I just confirm the name on the script?",
      "Could you tell me your first and last name?",
      "Can you spell your surname for me?",
      "Is this for you or someone else?",
      "Could I confirm who I'm speaking with?",
      "Can I confirm your name before we start?",
      "Sorry, what was your name again?",
      "Can I just double check your name?",
      "Just to make sure I've got the right person, what's your full name?",
      "name?",
      "May I please have your full name?",
      "Could you confirm the patient's name for me?",
      "Just need your name for the records.",
      "Who am I speaking to today?",
      "What name is the script under?",
    ],
    confirm_age: [
      "What's your date of birth?",
      "Can I grab your DOB?",
      "How old are you?",
      "When were you born?",
      "Can I confirm your birthday please?",
      "And your date of birth is?",
      "Could you tell me your date of birth?",
      "What's your age?",
      "Could I also get your date of birth please?",
      "And how old are you now?",
      "What's the DOB on this one?",
      "dob please",
      "May I have your date of birth?",
      "What is the patient's age?",
      "And what's your birthdate?",
      "How old is the patient?",
      "Can you please tell me your date of birth, is for check.",
    ],
    allergies: [
      "Do you have any allergies?",
      "Are you allergic to any medications?",
      "Any allergies I should know about?",
      "Have you ever had a reaction to a medicine?",
      "Has any medicine ever given you a rash or made you unwell?",
      "Is there any medicine you can't take?",
      "Any drug allergies?",
      "Have you had any bad reactions to antibiotics or other tablets before?",
      "Just checking, you don't have any medication allergies, do you?",
      "Have any tablets ever not agreed with you or given you a reaction?",
      "Are there any meds you've reacted to in the past?",
      "any allergys?",
      "Do you have any known drug allergies?",
      "Have you ever experienced an adverse reaction to a medication?",
      "Any meds you're allergic to at all?",
      "Have you got any allergy to medicine?",
      "Has anything ever given you a reaction, like a rash or swelling, when you took it?",
    ],
    current_medicines: [
      "Are you taking any other medicines?",
      "What else do you take?",
      "Do you take anything regularly?",
      "Are you on any vitamins, supplements or herbal products?",
      "Are you on any other tablets at the moment?",
      "Do you take anything over the counter?",
      "What medications are you currently on?",
      "Are you using any other prescriptions or anything from the supermarket?",
      "What other meds are you on at the moment?",
      "Are you taking anything else, even stuff you buy yourself like vitamins?",
      "Do you use any natural or herbal remedies?",
      "u on any other meds?",
      "Are you currently taking any other prescribed or non-prescribed medicines?",
      "What regular medicines do you have at home?",
      "What else are you taking at the moment, prescriptions or anything over the counter?",
      "Do you take other medicine every day?",
      "Anything else you're on, like supplements?",
    ],
    teach_back: [
      "Can you tell me how you're going to take it?",
      "Just to check I've explained it properly, can you repeat it back to me?",
      "So what are you going to do when you get home?",
      "Can you run me through the plan?",
      "In your own words, how will you use it?",
      "Could you explain back to me what we talked about?",
      "Just so I know I was clear, how are you going to take these?",
      "Can you summarise what I told you?",
      "Okay, just so I'm sure, could you tell me in your words how you'll take them?",
      "Can you walk me through how you're going to use this at home?",
      "Before you go, can you tell me back what the plan is?",
      "can u tell me how ur gonna take it",
      "To ensure I have explained this clearly, could you describe how you will take this medicine?",
      "Could you repeat back to me how you'll be using it?",
      "Just so we're on the same page, how are you gonna take these when you get home?",
      "Can you please explain me how you will take this medicine?",
      "Mind running me through how you'll take them?",
    ],
    invite_questions: [
      "Do you have any questions?",
      "Any questions for me?",
      "Is there anything else you'd like to ask?",
      "Anything else I can help you with?",
      "Do you have any concerns?",
      "Is there anything you're unsure about?",
      "Any other questions before you go?",
      "Does that all make sense? Any questions?",
      "Was there anything else you wanted to ask me?",
      "Have you got any questions at all?",
      "Is there anything else you're worried about?",
      "questions?",
      "Do you have any further questions regarding your medication?",
      "Is there anything else you would like to discuss?",
      "Anything you want to ask me before you head off?",
      "Do you have questions for me?",
      "Is there anything else on your mind?",
    ],
  },
};

export const CASE_PHRASINGS: Record<string, PhrasingBank> = {
  "case-1": {
    says: {
      purpose: [
        "This is an antibiotic for your infection.",
        "It's erythromycin, it treats the bacterial infection you've got.",
        "These capsules are to clear up your chest infection.",
        "It's for the infection the doctor saw you about.",
        "This antibiotic kills the bacteria causing your infection.",
        "It'll help fight off the infection.",
        "The doctor prescribed this to treat an infection.",
        "So basically this antibiotic is to get rid of the infection you've got.",
        "The erythromycin is treating the bacterial infection your GP picked up.",
        "its an antibiotic for ur infection",
        "This medication is indicated for the treatment of your bacterial infection.",
        "This antibiotic is used to treat the infection you have.",
        "The capsules are going to help get rid of the bacteria causing your infection.",
      ],
      explain_hold: [
        "It's too early for this repeat, so I can't give it to you until I've spoken to your doctor.",
        "You only got this four days ago, so I need to hold it and check with the prescriber first.",
        "This was dispensed recently so I'm going to hold off supplying it until I've contacted your GP.",
        "Your last supply was only 4 days ago — I can't supply another one today without checking with your doctor.",
        "It's a bit soon for another repeat. I'll need to call the doctor before I can dispense it.",
        "I can't hand this over yet because it's too early; I need to confirm with your doctor.",
        "Because you got it so recently, I'm going to hold the script and ring your doctor to clarify.",
        "This repeat is early so I won't be able to supply it until I've talked to your prescriber.",
        "Just letting you know, it's only been four days since your last lot so it's too early, I'll have to hold it while I call your doctor.",
        "Unfortunately this repeat is being requested too early, so I'm not able to supply it before I've checked with your GP.",
        "Your last fill was really recent, so I'll need to hold this one and speak to the doctor first.",
        "this repeat is too early, i cant supply it until i talk to ur doctor",
        "As your previous supply was only four days ago, I am unable to dispense this repeat until I have consulted your prescriber.",
        "So I had a look and it was only dispensed four days ago which is too early, so I'm going to hold onto it and give your doctor a ring before I can supply it.",
        "It's probably a bit too soon for this repeat, I'd rather hold it for now and check with your prescriber first.",
      ],
      next_steps: [
        "I'll give your doctor a call and let you know what they say.",
        "Once I've spoken to the prescriber I'll ring you with an update.",
        "I'll contact your GP today and get back to you after.",
        "We'll phone you as soon as we hear back from the doctor.",
        "I'll let you know the outcome once I've talked to your doctor.",
        "After I speak with your doctor I'll call you to tell you what's happening.",
        "Leave it with me, I'll call the prescriber and then call you back.",
        "I'll ring the surgery today and give you a call back once I've heard from them.",
        "I'll let you know as soon as I've had a chat with your doctor.",
        "ill call ur dr and let u know",
        "Once I have spoken with your prescriber, I will contact you to advise you of the outcome.",
        "I'm going to speak to your doctor and then I'll let you know what's happening.",
        "You'll be updated by us once the doctor has got back to me.",
      ],
      allergic_reaction_safety: [
        "If you get any swelling or trouble breathing, get medical help straight away.",
        "If you break out in a rash or hives, see a doctor.",
        "Call 000 if your face or lips swell up or you can't breathe properly.",
        "If you have an allergic reaction, go to the hospital.",
        "Watch out for a rash, swelling or wheezing, and get urgent help if that happens.",
        "If your throat feels tight or you're struggling to breathe, call an ambulance.",
        "Any signs of an allergic reaction like hives or swelling, get help immediately.",
        "If your face or tongue starts swelling up or you're short of breath, go straight to emergency.",
        "Should you notice hives or a rash spreading, get medical help quickly.",
        "if u get swelling or cant breathe call 000",
        "Should you experience facial swelling or difficulty breathing, please seek emergency medical attention.",
        "If you get any swelling of the lips or face or you're struggling to breathe, you'd want to get urgent help.",
        "Emergency help is needed if you have trouble breathing or your throat swells.",
      ],
      directions: [
        "Take one capsule four times a day.",
        "It's one capsule four times daily.",
        "Take 1 capsule every 6 hours.",
        "You take one of these four times each day.",
        "One cap, four times a day.",
        "Take one capsule qid.",
      ],
      complete_course: [
        "Make sure you finish the whole course.",
        "Keep taking them until they're all gone, even if you feel better.",
        "Don't stop early — finish the course.",
        "It's important to complete the course of antibiotics.",
        "Take all of them, even once you start feeling better.",
      ],
      nausea_advice: [
        "It might make you feel a bit sick.",
        "Some people get nausea with it.",
        "It can upset your stomach, so let us know if it's bad.",
        "It can make you queasy.",
        "Take it on an empty stomach.",
        "It's best taken an hour before food.",
      ],
    },
    mustNot: {
      nausea_advice: ["Don't worry, it won't upset your stomach at all."],
      explain_hold: [
        "It's a bit early but I'll give it to you anyway.",
        "Have you spoken to your doctor about this repeat?",
        "It was dispensed four days ago, here you go.",
      ],
      directions: [
        "Take two capsules four times a day.",
        "Take one capsule three times a day.",
        "Take one capsule twice daily.",
      ],
      complete_course: [
        "You can stop taking them once you feel better.",
        "Are you going to finish the course?",
      ],
      allergic_reaction_safety: ["Do you get a rash with any antibiotics?"],
    },
  },

  "case-2": {
    says: {
      dose_plan: [
        "Keep following the dosing plan from your anticoagulation clinic.",
        "Take it as directed by the clinic.",
        "Stick to the dose in your warfarin book.",
        "Follow your yellow book for how much to take each day.",
        "Take the dose your clinic tells you, not a fixed amount from memory.",
        "Keep taking the amount the anticoagulation clinic told you.",
        "Just follow your current dose plan from the clinic.",
        "Just keep taking whatever dose the anticoag clinic has you on at the moment.",
        "The clinic will tell you your dose, so follow what's written in your warfarin book.",
        "keep following ur clinic dose plan",
        "Please continue to take the dose specified by your anticoagulation clinic.",
        "I'd keep taking the warfarin exactly as the clinic has directed.",
        "Your dose is set by the anticoagulation clinic so stick with that plan.",
      ],
      inr_monitoring: [
        "Make sure you keep up with your INR blood tests.",
        "Don't miss your INR checks.",
        "You'll need regular blood tests to check your INR.",
        "Keep going to your INR appointments.",
        "Get your INR tested when it's due.",
        "Your blood needs checking regularly while you're on warfarin, so keep your blood test appointments.",
        "Remember your regular INR monitoring at the clinic.",
        "It's really important you keep having your INR checked regularly.",
        "Make sure you get your blood tested for your INR when the clinic asks.",
        "dont miss ur INR tests",
        "It is essential that you continue to attend your scheduled INR monitoring.",
        "You'll need to keep getting your INR checked regularly with blood tests.",
        "Regular INR blood tests are really important with warfarin.",
      ],
      interactions: [
        "Avoid ibuprofen and aspirin while you're on warfarin.",
        "Don't take Nurofen with this.",
        "Check with us before starting any new medicines, including over-the-counter ones.",
        "Anti-inflammatories like ibuprofen can make you bleed more, so avoid them.",
        "Always ask a pharmacist before taking something new.",
        "Stay away from aspirin and ibuprofen.",
        "Paracetamol is fine for headaches but avoid ibuprofen.",
        "Talk to us before you start or stop any other medicines because they can affect warfarin.",
        "Please steer clear of Nurofen or aspirin because they can make you bleed.",
        "If you want to start anything new, even from the supermarket, check with a pharmacist first.",
        "Anti-inflammatory painkillers are a no-go with warfarin, stick to paracetamol.",
        "no ibuprofen or aspirin with this",
        "Please consult a pharmacist before commencing any new medicines, as many interact with warfarin.",
        "I'd avoid taking any anti-inflammatories like Nurofen while you're on this.",
        "Before you start any new medicine, please check with us first because warfarin interacts with lots of things.",
      ],
      bleeding_safety: [
        "If you notice any unusual bleeding or bruising, contact your doctor.",
        "Get urgent help if you have black stools or vomit blood.",
        "If you hit your head, go to hospital straight away.",
        "Seek help if the bleeding won't stop.",
        "If you're bleeding a lot or it won't stop, go to emergency.",
        "Watch for blood in your urine or black poo and see a doctor urgently.",
        "If you vomit blood or your poo turns black, go to emergency straight away.",
        "Any bleeding that doesn't stop or big unexplained bruises, see a doctor urgently.",
        "if bleeding wont stop go to ED",
        "If you experience black stools or vomit blood, please seek urgent medical attention.",
        "Unusual bruising or bleeding should be checked by a doctor straight away.",
        "If you have a fall and hit your head, you should go to hospital to be checked.",
      ],
    },
    mustNot: {
      bleeding_safety: ["A bit of bleeding is normal, no need to see anyone about it."],
      interactions: [
        "Ibuprofen is fine to take with warfarin.",
        "Do you ever take ibuprofen?",
      ],
      inr_monitoring: ["When was your last INR test?"],
    },
  },

  "case-3": {
    says: {
      purpose: [
        "This antibiotic is for Liam's ear infection.",
        "It's amoxicillin to treat his bacterial infection.",
        "It'll help clear up his infection.",
        "The mixture treats the infection the doctor found.",
        "It kills the bacteria that are causing Liam's infection.",
        "This is the antibiotic for Liam's bacterial chest infection.",
        "its for liams infection",
        "This antibiotic is prescribed to treat Liam's bacterial infection.",
        "The amoxicillin is being used to treat his bacterial infection.",
      ],
      directions: [
        "Give Liam 10 mL three times a day for 10 days.",
        "It's 10mls three times daily for ten days.",
        "Give him ten millilitres three times a day, for 10 days.",
        "Give 10 mL every 8 hours for 10 days.",
        "Three times a day he needs 10 mL, and keep going for 10 days.",
        "Give 10 mls tds for 10 days.",
        "Ten mils, three times a day, for the next ten days.",
        "10ml morning, afternoon and night for 10 days.",
        "So Liam needs 10 mL of the liquid three times a day, and you'll keep going for 10 days.",
        "It's ten mL, three times daily, for a total of ten days.",
        "Give him 10ml in the morning, afternoon and at night, for 10 days straight.",
        "10ml tds for 10 days",
        "Please administer 10 millilitres three times daily for ten days.",
        "He's to have 10 mL three times a day and it's a 10 day course.",
        "Ten mls is given three times daily for ten days.",
      ],
      liquid_handling: [
        "Shake the bottle well before each dose.",
        "Use the oral syringe to measure it, not a kitchen spoon.",
        "Please don't use a teaspoon — use the syringe we gave you.",
        "Give it a good shake first.",
        "Measure each dose with the measuring cup.",
        "Use the dosing syringe so the dose is accurate.",
        "Kitchen spoons aren't accurate, so use the syringe.",
        "Give the bottle a really good shake and use the syringe to get the dose right.",
        "Try not to use a normal spoon, the oral syringe is much more accurate.",
        "shake well and use the syringe",
        "Please shake the bottle before each dose and measure it using the oral syringe provided.",
        "It should be shaken well before each dose.",
        "I'd use the syringe rather than a teaspoon because it's more accurate.",
      ],
      storage: [
        "Keep it in the fridge.",
        "Store it in the refrigerator once it's been mixed.",
        "It needs to be kept refrigerated.",
        "Pop it in the fridge when you get home.",
        "Keep the bottle in the fridge, but don't freeze it.",
        "After it's made up it should go in the fridge.",
        "Store it in the fridge between 2 and 8 degrees.",
        "Once it's mixed it has to live in the fridge.",
        "Make sure it's kept refrigerated, not in the cupboard.",
        "keep in fridge",
        "This suspension should be stored in the refrigerator.",
        "It has to be kept in the fridge once it's been made up.",
        "Store this one in the refrigerator please.",
      ],
      complete_course: [
        "Finish the whole bottle even if he feels better.",
        "Keep giving it for the full 10 days.",
        "Don't stop early, even if Liam seems better.",
        "Make sure he completes the course.",
        "Keep going until the course is finished.",
        "finish the whole course",
        "Please ensure Liam completes the full course, even if his symptoms improve.",
        "Even if he's feeling heaps better, keep giving it until the course is finished.",
        "The whole course should be completed.",
      ],
      common_effects: [
        "It might give him an upset stomach or diarrhoea.",
        "Some kids get a bit of diarrhoea on it.",
        "He might feel sick.",
        "Common side effects are nausea and loose stools.",
        "It can cause a tummy upset, so let us know if it's bad.",
        "If he gets runny poos, keep his fluids up.",
        "He could end up with a bit of an upset tummy or runny poo.",
        "Diarrhoea is a common side effect, so watch for that.",
        "might get diarrhoea",
        "Common adverse effects include nausea and diarrhoea.",
        "Some upset tummy or diarrhoea can happen with this one.",
        "He may feel a bit sick or have loose stools.",
      ],
      reaction_safety: [
        "If he gets a rash or any swelling, see a doctor.",
        "If Liam has trouble breathing or his face swells, call 000.",
        "Look out for hives or a rash and get medical help.",
        "Any signs of an allergic reaction, take him to hospital.",
        "If his lips or tongue swell, get urgent help.",
        "If Liam's lips swell or he struggles to breathe, call an ambulance.",
        "A rash could mean an allergy, so get him seen by a doctor.",
        "if he gets a rash see a dr",
        "If Liam develops a rash or any swelling, please seek medical attention.",
        "If he breaks out in hives or his face swells, get him to a doctor urgently.",
        "Medical help should be sought if Liam gets a rash or has trouble breathing.",
      ],
    },
    mustNot: {
      common_effects: ["He won't get any side effects from this."],
      directions: [
        "Give him 5 mL three times a day for 10 days.",
        "Give him 10 mL twice a day for 10 days.",
        "Give 10 mL three times a day for 5 days.",
        "How much have you been giving him?",
      ],
      liquid_handling: ["A kitchen teaspoon is fine to measure it."],
      storage: ["Don't put it in the fridge."],
    },
  },

  "case-4": {
    says: {
      sedative_alcohol_history: [
        "How much alcohol do you drink in a week?",
        "Do you drink alcohol at all?",
        "Can I ask about your drinking?",
        "Are you taking anything else to help you sleep?",
        "Do you use any other sleeping tablets or sedatives?",
        "Have you been drinking recently?",
        "How often do you have a drink?",
        "Can I ask how much you've been drinking lately?",
        "Are you using anything else for sleep at the moment?",
        "how much do u drink",
        "Could you tell me about your current alcohol intake?",
        "Do you have any alcohol most nights?",
        "Are you on any other sedatives or sleeping pills?",
      ],
      explain_hold: [
        "I can't supply this today until I've spoken to your doctor.",
        "I need to hold the prescription and contact your GP first.",
        "I'm not able to give you these until I check with the prescriber.",
        "I'll have to hold onto this script and call your doctor.",
        "Before I can dispense it I need to talk to your doctor.",
        "I won't be able to hand this over today — I need to clarify it with your GP.",
        "I can't give it to you today, I need to speak with your doctor first.",
        "I'm really sorry but I'm going to have to hold this until I've spoken to your doctor.",
        "I won't be able to dispense these today, I need to clarify a few things with your GP first.",
        "cant give u these today, need to call ur doctor",
        "I am unable to supply this medication until I have clarified the prescription with your doctor.",
        "I'm not comfortable supplying this today, I need to speak to your doctor first.",
        "The prescription is being held until I've checked with your GP.",
      ],
      explain_risk: [
        "Mixing alcohol with sleeping tablets can make you very drowsy and slow your breathing.",
        "Drinking while taking temazepam is dangerous.",
        "Alcohol and these tablets together increase the risk of overdose.",
        "Alcohol plus temazepam can cause too much sedation.",
        "It's risky to combine them with drinking.",
        "Taking them after drinking could affect your breathing.",
        "Having alcohol with temazepam really increases the risk of oversedation.",
        "The combination of drinking and these tablets can be dangerous for your breathing.",
        "alcohol plus these is dangerous",
        "Combining alcohol with temazepam increases the risk of sedation and respiratory depression.",
        "Mixing these with alcohol can really knock you out and affect your breathing.",
        "It's risky to have alcohol with temazepam because you could get too sedated.",
      ],
      next_steps_empathy: [
        "I know this is frustrating — I'll call your doctor and let you know.",
        "I'll contact the prescriber today and get back to you.",
        "Sorry about the hassle. I'll update you once I've spoken to them.",
        "I'll give your GP a ring and follow up with you.",
        "We'll let you know what happens next after talking with your doctor.",
        "I understand it's annoying; I'll phone the doctor and call you back.",
        "I understand that's not what you wanted to hear, I'll contact your GP and let you know what happens.",
        "Once I've spoken to the doctor I'll get back to you today.",
        "sorry, ill call ur dr and get back to u",
        "I appreciate this is inconvenient. I will contact your doctor and update you as soon as possible.",
        "I know it's a pain, but I'll contact your doctor and update you today.",
        "Sorry about this, I'll let you know what happens after I've called your GP.",
      ],
    },
    mustNot: {
      explain_hold: ["Can I call your doctor about this?"],
      explain_risk: ["Having a drink with these is fine."],
    },
  },

  "case-5": {
    says: {
      renal_history: [
        "Have you had your kidney function checked recently?",
        "Do you know your latest kidney results?",
        "Have you been told you have kidney problems?",
        "Have you been unwell or dehydrated lately?",
        "When was your last blood test for your kidneys?",
        "Have you had any vomiting or diarrhoea recently?",
        "Has your doctor mentioned anything about your kidneys recently?",
        "Have you been sick with vomiting or diarrhoea lately?",
        "any kidney problems?",
        "Have you had your renal function assessed recently?",
        "Have you been told anything about your kidney function lately?",
        "Have you been unwell or not drinking much recently?",
      ],
      explain_hold: [
        "I need to hold this and contact your doctor before I supply it.",
        "I can't dispense it until I've checked with the prescriber.",
        "I'm going to hold the prescription and ring your GP first.",
        "I won't be able to supply this today until the doctor reviews it.",
        "Before I can give you these I need to speak with your doctor.",
        "I'm going to have to hold off on this until I've spoken with your prescriber.",
        "I can't hand this over today, I need to check a couple of things with your doctor.",
        "i have to hold this and call ur doctor",
        "I will need to withhold supply until I have discussed this with your prescriber.",
        "I'll have to hold this one until I've spoken to your prescriber.",
        "This can't be supplied until I've checked with your doctor.",
      ],
      explain_concern: [
        "Cimetidine can raise your metformin levels, and with your kidney function that's a concern.",
        "The cimetidine interacts with metformin, and your kidneys aren't clearing it as well.",
        "Your eGFR is lower and cimetidine increases metformin, so the doctor needs to review it.",
        "Cimetidine plus reduced renal function could make the metformin build up.",
        "Because of your kidneys, the cimetidine could push your metformin levels too high.",
        "The cimetidine can increase how much metformin is in your system, and with reduced kidney function that's risky.",
        "Your kidney function is lower and the cimetidine interacts with metformin, so the doctor needs to look at it.",
        "cimetidine increases metformin and ur kidneys are reduced",
        "Cimetidine may raise metformin concentrations, which is a concern given your reduced renal function.",
        "The cimetidine could cause the metformin to build up, especially with your kidney function being lower.",
        "With reduced kidney function, cimetidine plus metformin is a concern.",
      ],
      next_steps: [
        "I'll contact your doctor and let you know.",
        "Don't change anything yourself for now — I'll call the prescriber.",
        "Keep taking your current medicines as usual until we hear back.",
        "I'll follow up with your GP and update you.",
        "I'll call you once I've spoken to the doctor.",
        "Don't stop anything yourself, I'll call the doctor and update you.",
        "Keep everything as it is for now and I'll let you know once I've heard back.",
        "dont change anything, ill call ur doctor",
        "Please do not make any changes yourself; I will contact your prescriber and inform you of the outcome.",
        "Just carry on with your usual medicines and I'll give you a call after I talk to the doctor.",
        "I'll follow up with your prescriber and let you know.",
      ],
    },
  },

  "case-6": {
    says: {
      pregnancy_check: [
        "Is there any chance you could be pregnant?",
        "Are you pregnant or breastfeeding?",
        "Can I check if you're pregnant or planning a pregnancy?",
        "Are you breastfeeding at the moment?",
        "Any chance of pregnancy?",
        "Before we go on, are you pregnant?",
        "I have to ask, is there any possibility you're pregnant?",
        "Are you currently breastfeeding or pregnant at all?",
        "any chance ur pregnant?",
        "May I ask whether you are pregnant or breastfeeding?",
        "Is there any chance at all that you're pregnant?",
        "Are you pregnant or trying for a baby?",
      ],
      directions: [
        "Take one tablet twice a day.",
        "One tablet in the morning and one at night.",
        "Take 1 tab bd.",
        "It's one tablet twice daily.",
        "Take one every 12 hours.",
        "One tablet two times a day.",
        "Take one tablet every twelve hours.",
        "You'll take one tablet twice a day, about twelve hours apart.",
        "It's one in the morning and one at night.",
        "1 tab bd",
        "Take one tablet twice daily.",
        "It's one tablet, twice a day.",
        "You're to take one tablet in the morning and one tablet at night.",
      ],
      water_upright: [
        "Take it with a full glass of water and stay upright for 30 minutes.",
        "Have a big glass of water with it and don't lie down for half an hour.",
        "Swallow it with a glass of water and stay upright afterwards.",
        "Take it with a full glass of water and don't lie flat after.",
        "Drink a full glass of water with the tablet and stay sitting up for 30 minutes.",
        "Make sure you have it with a full glass of water and don't lie down for at least half an hour.",
        "Swallow it with plenty of water and stay upright afterwards.",
        "take with full glass of water and stay upright 30 mins",
        "Please take each dose with a full glass of water and remain upright for thirty minutes afterwards.",
        "It should be taken with a full glass of water and you should stay upright for thirty minutes.",
        "Have a big glass of water with it, and don't lie down straight after.",
      ],
      separation: [
        "Take your antacid at least 2 hours apart from the doxycycline.",
        "Separate it from iron, calcium or dairy by two hours.",
        "Don't take it with milk — leave a two hour gap.",
        "Keep your multivitamin two hours away from this tablet.",
        "Space your antacids and the antibiotic a couple of hours apart.",
        "Leave two hours between the doxycycline and your antacid.",
        "Try to keep your antacids and any dairy at least two hours away from it.",
        "Don't have it with milk or your calcium, leave a gap of two hours.",
        "keep antacids 2 hrs apart",
        "Please separate doses of antacids, iron or calcium supplements from doxycycline by at least two hours.",
        "Your antacid shouldn't be taken within two hours of the doxycycline.",
        "Leave a two hour gap between this and any iron or calcium.",
      ],
      sun_precautions: [
        "It can make you burn more easily, so wear sunscreen.",
        "Avoid too much sun and cover up.",
        "Use SPF 50 and a hat when you're outside.",
        "You'll be more sensitive to the sun on this.",
        "Protect your skin from the sun while you're taking it.",
        "Be careful in the sun, it can make you photosensitive.",
        "Slip slop slap, it can make you sunburn more easily.",
        "Wear sunscreen because this can make your skin sensitive to sunlight.",
        "wear sunscreen",
        "Doxycycline may cause photosensitivity, so please use sun protection.",
        "You might burn more easily in the sun, so cover up and wear sunscreen.",
        "Sun protection is important while you're on doxycycline.",
      ],
    },
    mustNot: {
      directions: [
        "Take two tablets twice a day.",
        "Take one tablet once a day.",
      ],
      water_upright: ["You can lie down straight after taking it."],
      separation: ["You can take it with your antacid, that's fine."],
    },
  },

  "case-7": {
    says: {
      opioid_tolerance: [
        "How long have you been on this dose?",
        "Have you had any drowsiness or breathing problems on it?",
        "Has your current dose been working without making you too sleepy?",
        "Are you used to taking this strength?",
        "How have you been going on the OxyContin?",
        "How have you been finding the OxyContin, any issues with drowsiness?",
        "How long have you been on this particular dose?",
        "how long uve been on this dose?",
        "Have you experienced any sedation or breathing difficulties on your current dose?",
        "How are you going on your current dose, any drowsiness?",
        "Has the OxyContin been making you sleepy or affecting your breathing?",
      ],
      directions_mr: [
        "Take one tablet every 12 hours and swallow it whole.",
        "Swallow it whole twice a day, don't crush or chew it.",
        "One tablet in the morning and one at night — never crush them.",
        "It's slow release so don't chew it; take one every twelve hours.",
        "Take it twice daily and swallow it whole.",
        "One every 12 hours, and don't break or crush it.",
        "Remember to take one tablet every twelve hours and swallow it whole, no chewing.",
        "Take one twice a day and make sure you don't crush it.",
        "1 tab every 12 hrs, swallow whole",
        "Take one tablet every twelve hours and swallow it whole; do not crush or chew it.",
        "It's one tablet every 12 hours, swallowed whole, and never crushed.",
        "Take one twice daily, and make sure it isn't chewed or crushed.",
      ],
      sedation_safety: [
        "Avoid alcohol with this.",
        "Don't drive if you feel drowsy.",
        "Don't drink while taking it.",
        "No driving or operating machinery if it makes you sleepy.",
        "Stay off the booze while you're on it.",
        "Be careful driving, it can make you sleepy.",
        "Don't get behind the wheel if you feel drowsy.",
        "Please don't drink alcohol with these, and avoid driving if you're drowsy.",
        "It can make you sleepy so don't drive or use machinery if you feel affected.",
        "no alcohol and dont drive if drowsy",
        "Please avoid alcohol and do not drive if you feel drowsy.",
        "Alcohol should be avoided with these.",
        "If it makes you drowsy, don't drive.",
      ],
      secure_storage: [
        "Keep them locked away from your grandchildren.",
        "Store them somewhere secure, out of reach of kids.",
        "Never share them with anyone.",
        "Bring any leftover tablets back to the pharmacy.",
        "Keep them in a locked cupboard.",
        "Make sure the grandkids can't get to them.",
        "Keep them somewhere locked so the grandkids can't reach them.",
        "Any tablets you don't need, return them to the pharmacy for safe disposal.",
        "keep them locked up",
        "Please store these tablets securely and return any unused medication to a pharmacy.",
        "They should be kept locked up away from the grandkids.",
        "Never give your tablets to anyone else.",
      ],
      respiratory_red_flags: [
        "If your breathing becomes slow or shallow, call 000.",
        "If someone can't wake you, they need to call an ambulance.",
        "Get urgent help if you're extremely drowsy or your lips turn blue.",
        "Call triple zero if you have trouble breathing.",
        "If you collapse or become unresponsive, get emergency help.",
        "Seek urgent care if your breathing is irregular.",
        "If your breathing gets really slow or someone can't wake you up, call triple zero.",
        "Blue lips or trouble breathing means calling an ambulance straight away.",
        "call 000 if breathing slows",
        "If you experience slowed breathing or cannot be roused, emergency services must be called.",
        "If your breathing becomes very slow or shallow, an ambulance needs to be called.",
        "Call triple zero straight away if you can't be woken up properly.",
      ],
    },
    mustNot: {
      respiratory_red_flags: ["Slow breathing is normal on these, don't worry about it."],
      secure_storage: ["It's fine to leave them out on the kitchen bench."],
      directions_mr: [
        "You can crush it if it's hard to swallow.",
        "Take one tablet three times a day and swallow it whole.",
      ],
      sedation_safety: ["Do you drink alcohol?"],
    },
  },

  "case-8": {
    says: {
      opioid_history: [
        "Have you used strong painkillers like morphine or oxycodone before?",
        "Have you ever used a fentanyl patch?",
        "Are you currently taking any opioids?",
        "Have you been on any opioid medicines before?",
        "What's your opioid tolerance like?",
        "Have you ever taken strong pain meds like oxycodone before?",
        "Are you on any opioid painkillers at the moment?",
        "used opioids before?",
        "Have you previously been prescribed any opioid analgesics?",
        "Have you had morphine or anything like that before?",
        "Are you taking any strong pain medicine at the moment?",
      ],
      explain_hold: [
        "I can't give you this patch until I've spoken to your doctor.",
        "I need to hold it and contact the prescriber urgently.",
        "I won't be able to supply the patch today — I need to check with your GP.",
        "I'm holding this prescription until I've clarified it with the doctor.",
        "Before I can dispense this I need to talk to your prescriber.",
        "I'm not able to give you this patch until I've spoken to your doctor.",
        "I have to hold this and call the prescriber before I can dispense it.",
        "cant supply the patch until i speak to ur dr",
        "I am unable to dispense this patch until I have spoken with your prescriber.",
        "I'm going to hold onto this patch for now and contact your doctor.",
        "The patch can't be supplied until I've spoken with your prescriber.",
      ],
      explain_risk: [
        "This patch can slow your breathing dangerously because you haven't used opioids before.",
        "Fentanyl is too strong to start on if you're opioid-naive.",
        "It could stop your breathing, since you're not used to opioids.",
        "Starting on this patch without being on opioids first can depress your breathing.",
        "For someone who isn't opioid tolerant, this can slow breathing to a dangerous level.",
        "Because you haven't used opioids before, this patch could slow your breathing dangerously.",
        "Fentanyl patches aren't safe for people who aren't opioid tolerant, it can stop your breathing.",
        "fentanyl could slow ur breathing since ur not used to opioids",
        "In a patient who is not opioid tolerant, this patch may cause dangerous respiratory depression.",
        "Since your body isn't used to opioids, this patch could make your breathing dangerously slow.",
        "It's a strong opioid and could depress your breathing because you're opioid naive.",
      ],
      interim_plan: [
        "Keep using your paracetamol for now and I'll call your doctor.",
        "Don't start the patch; I'll contact the prescriber and let you know.",
        "Stick with your usual pain relief until we hear back.",
        "I'll call your doctor and update you — don't apply any patch in the meantime.",
        "For now just keep using your paracetamol and I'll let you know what the doctor says.",
        "Please don't put on any patch until I've spoken to the doctor.",
        "keep using ur paracetamol for now",
        "Please continue your current pain relief while I contact your doctor.",
        "Just keep using your paracetamol and I'll be in touch once I've talked to the doctor.",
        "Don't start any patch in the meantime; I'll update you.",
      ],
    },
    mustNot: {
      explain_risk: ["The patch is perfectly safe for you."],
      interim_plan: ["Go ahead and start the patch tonight."],
    },
  },

  "case-9": {
    says: {
      explain_hold: [
        "The prescriber number on the script doesn't match our records, so I need to verify it before supplying.",
        "Something about this prescription doesn't look right, so I have to check it before I can supply it.",
        "I need to hold this because the doctor's details don't match, and confirm it with the clinic.",
        "The prescriber number is wrong so I can't supply until I've verified it.",
        "I'm going to hold the prescription while I authenticate the prescriber details.",
        "The prescriber number on here doesn't match what we have, so I need to hold it and verify it.",
        "Something doesn't look right with the prescription, so I'll have to check it before I can supply.",
        "prescriber number doesnt match, need to verify",
        "The prescriber details do not match our records, so I must hold this prescription and verify it.",
        "The doctor's number on this doesn't match our directory, so I'll need to hold it and verify it first.",
        "This prescription looks a bit suspicious, so I'm going to hold it and check it's legitimate.",
      ],
      independent_contact: [
        "I'll call the clinic using the number we have on file, not the one on the prescription.",
        "I'll look up the practice's phone number myself rather than use the one written here.",
        "We'll contact the doctor through our verified directory.",
        "I won't ring the number on the script — I'll use our own records.",
        "I'll check with the clinic on a number we already know is genuine.",
        "I'll call the clinic on the number from our records rather than the one on the script.",
        "I'm going to use the phone number we already have for the practice, not the one written on this.",
        "ill call the clinic on our number not the one on the script",
        "I will contact the practice using independently verified details rather than the number on the prescription.",
        "I'll call the clinic on the number we already have, not the one printed on the script.",
        "I'll use the contact details from our records to verify it.",
      ],
      follow_up: [
        "I'll document what happens and let you know.",
        "I'll call you once I've spoken to the clinic.",
        "We'll update you as soon as we hear back.",
        "I'll record the outcome and get back to you.",
        "I'll give you a call once I've spoken to the clinic.",
        "I'll write up what happened and let you know the outcome.",
        "ill call u once i hear back",
        "I will document the outcome and contact you once the prescriber has responded.",
        "I'll let you know once I've heard back from the clinic.",
        "I'll document everything and update you.",
      ],
    },
    mustNot: {
      independent_contact: ["I'll just ring the number printed on the prescription."],
    },
  },

  "case-10": {
    says: {
      weekly_history: [
        "What day do you usually take your methotrexate?",
        "How often do you normally take it?",
        "When do you take your folic acid?",
        "Do you take it once a week?",
        "How have you been taking your methotrexate?",
        "Which day of the week do you normally take your methotrexate?",
        "How do you usually take it, weekly?",
        "what day do u take it?",
        "How frequently do you normally take your methotrexate?",
        "Which day do you have your methotrexate?",
        "Is it normally a once weekly tablet for you?",
      ],
      explain_hold: [
        "This says daily but methotrexate should be once a week — taking it every day is dangerous, so I need to check with your doctor.",
        "The daily direction is an error; I'm holding it until the prescriber confirms weekly dosing.",
        "Taking methotrexate every day can be fatal, so I'll hold this and contact your doctor.",
        "The label says daily, which is wrong — it's meant to be weekly. I'll confirm with the prescriber.",
        "Daily methotrexate is toxic, so I need to clarify this with your doctor before supplying.",
        "The label says daily but it should be once weekly, which is a dangerous error, so I'll hold it and contact your doctor.",
        "Methotrexate taken every day can be really toxic, so I need to confirm this with your doctor before I supply it.",
        "daily is wrong its meant to be weekly, holding it and calling ur dr",
        "Daily methotrexate is a dangerous error; I will withhold supply and confirm the weekly dose with your prescriber.",
        "It says daily here but methotrexate should be weekly, taking it daily can be toxic, so I'm holding it until I check with your doctor.",
        "Daily dosing is wrong for methotrexate and dangerous, so I'll confirm the weekly dose with your doctor before supplying.",
      ],
      red_flags: [
        "If you get mouth ulcers, a fever or a sore throat, get advice urgently.",
        "Watch for unusual bruising or bleeding and see a doctor.",
        "Shortness of breath or a severe rash needs urgent attention.",
        "Tell us straight away if you get a fever or an infection.",
        "Mouth sores or unexplained bruising are warning signs — get checked.",
        "If you get a fever, mouth ulcers or unusual bruising, get checked urgently.",
        "Shortness of breath or a new rash need urgent attention.",
        "fever or mouth ulcers see a dr asap",
        "Please seek urgent medical advice if you develop a fever, mouth ulcers or unusual bruising.",
        "If you get mouth ulcers or a fever, you need to see a doctor quickly.",
        "Any unusual bruising or bleeding should be checked urgently.",
      ],
    },
    mustNot: {
      red_flags: ["Mouth ulcers are nothing to worry about."],
      explain_hold: ["Keep taking it daily as the label says."],
    },
  },

  "case-11": {
    says: {
      toxicity_assessment: [
        "Have you been vomiting or had diarrhoea, and have you taken any ibuprofen?",
        "Are you keeping fluids down, and have you used anti-inflammatories like Nurofen?",
        "Have you been dehydrated, and have you been taking ibuprofen at all?",
        "Any vomiting or diarrhoea, and any ibuprofen or naproxen lately?",
        "Have you been able to keep fluids down, and have you taken any Nurofen or ibuprofen?",
        "Have you been vomiting much, and have you used any anti-inflammatories?",
        "been vomiting? taken any nurofen?",
        "Have you experienced vomiting or diarrhoea, and have you taken any NSAIDs such as ibuprofen?",
        "Have you been vomiting or had diarrhoea, and have you taken any Nurofen for it?",
        "Have you been keeping fluids up, and have you had any anti-inflammatories like ibuprofen?",
      ],
      urgent_plan: [
        "You need to see a doctor urgently today.",
        "These symptoms could mean lithium toxicity — please go to the emergency department now.",
        "I'd like you to get medical help straight away.",
        "Please get checked at the hospital today.",
        "This needs urgent medical assessment right now.",
        "With the shaking and unsteadiness you need to see a doctor straight away today.",
        "I think you should go to the emergency department now to get checked.",
        "u need to see a dr today",
        "Given these symptoms, you require urgent medical assessment today.",
        "You should really go to the hospital today to get checked.",
        "I'd like you to see a doctor urgently today.",
      ],
      interaction_explanation: [
        "Being dehydrated from the stomach bug can raise your lithium levels.",
        "Ibuprofen can increase the lithium level in your blood.",
        "Vomiting and diarrhoea can make lithium build up.",
        "The ibuprofen and the dehydration together can make lithium toxic.",
        "When you're dehydrated your lithium level can rise and become toxic.",
        "Ibuprofen can push your lithium levels up.",
        "dehydration can raise ur lithium",
        "Dehydration and NSAIDs can both increase lithium concentrations.",
        "Being dehydrated can make your lithium level go up.",
        "Ibuprofen can increase your lithium levels.",
      ],
    },
    mustNot: {
      interaction_explanation: ["Ibuprofen won't affect your lithium at all."],
      urgent_plan: ["Just keep taking your lithium as usual."],
    },
  },

  "case-12": {
    says: {
      dose_factors: [
        "Why do you take Eliquis, and do you know your weight and kidney function?",
        "Is it for atrial fibrillation? And what's your weight?",
        "What's it for, and have you had your kidneys checked recently?",
        "What do you take it for, and do you know your latest kidney results?",
        "What do you take the Eliquis for, and do you know your weight?",
        "Do you know your latest kidney function results, and is this for AF?",
        "whats it for and whats ur weight?",
        "What is the indication for your apixaban, and are you aware of your weight and renal function?",
        "What are you taking Eliquis for, and do you know your weight?",
        "Is this for atrial fibrillation, and have you had your kidneys checked lately?",
      ],
      explain_hold: [
        "The dose has gone up from 2.5 to 5 mg, so I need to hold it and check with your doctor.",
        "I can't supply the higher strength until I've confirmed the dose with the prescriber.",
        "This is a different dose from before, so I'll hold it and call your GP.",
        "The 5 mg dose might be too high for you, so I'm not going to supply it until I've spoken to your doctor.",
        "Your dose has gone up to 5 mg, so I need to hold it and check with your doctor first.",
        "I'm not able to supply the 5 mg until I confirm the dose with your prescriber.",
        "5mg dose looks high, holding it til i check with ur dr",
        "Given the dose change, I will withhold supply until I have confirmed the strength with your prescriber.",
        "Your dose has changed to 5 mg, so I'll hold it for now and check with your doctor.",
        "The strength is different to last time, so this can't be supplied until I've confirmed it with your prescriber.",
      ],
      bleeding_interaction: [
        "Naproxen with Eliquis increases your risk of bleeding.",
        "Taking naproxen alongside Eliquis can make you bleed more easily.",
        "Get urgent help if you notice black stools or blood in your urine.",
        "Seek help straight away for bleeding that won't stop or a sudden severe headache.",
        "Anti-inflammatories like naproxen raise the bleeding risk with a blood thinner.",
        "Taking naproxen with Eliquis raises your risk of bleeding.",
        "If you notice black poo or blood in your wee, get help straight away.",
        "naproxen and eliquis = bleeding risk",
        "Please seek urgent help if you notice black stools, blood in your urine or a sudden severe headache.",
        "Naproxen and Eliquis together increase the risk of bleeding.",
        "Get help straight away if you notice black stools or a sudden bad headache.",
      ],
    },
    mustNot: {
      bleeding_interaction: ["Naproxen is fine to keep taking with Eliquis."],
    },
  },

  "case-13": {
    says: {
      two_item_orientation: [
        "There are two different medicines here.",
        "You've got two items today — the metformin and the sitagliptin.",
        "These are separate medicines that work differently.",
        "Let me go through each one separately.",
        "One is the metformin and the other is the sitagliptin; they do different jobs.",
        "So you've got two different diabetes medicines here.",
        "I'll go through each of these separately.",
        "2 different meds here",
        "You have been prescribed two separate medicines today, which I will explain in turn.",
        "You've got two medicines today and they work in different ways.",
        "There are two separate tablets here.",
      ],
      metformin_xr_admin: [
        "Swallow the metformin tablets whole, don't crush or chew them.",
        "Don't split the metformin, it's extended release.",
        "Take them whole — no halving them.",
        "These need to be swallowed whole.",
        "Never break the metformin tablets, even though they're big.",
        "The metformin is slow release, so you need to swallow it whole, don't break it.",
        "Please don't crush or chew the metformin tablets.",
        "swallow the metformin whole",
        "The extended-release metformin tablets must be swallowed whole and not crushed.",
        "The metformin tablets shouldn't be crushed or chewed, swallow them whole.",
        "Please don't split the metformin.",
      ],
      metformin_gi_advice: [
        "Take the metformin with your evening meal.",
        "Have them with food to avoid an upset stomach.",
        "It can cause diarrhoea at first, so take it with meals.",
        "Taking it after dinner helps with any stomach upset.",
        "Having the metformin with food can help with stomach upset.",
        "Take your metformin with dinner.",
        "take metformin with food",
        "Taking metformin with meals can reduce gastrointestinal side effects.",
        "The metformin is best taken with your meal to avoid an upset stomach.",
        "Take metformin with food.",
      ],
      sitagliptin_dose: [
        "Take one sitagliptin tablet once a day.",
        "The Januvia is one tablet daily.",
        "One sitagliptin every day.",
        "Sitagliptin — just one a day, with or without food.",
        "For the sitagliptin you just take one tablet once daily.",
        "Januvia is one tablet every day.",
        "1 sitagliptin daily",
        "Take one sitagliptin tablet once daily.",
        "It's one sitagliptin tablet a day.",
        "Sitagliptin is taken once a day, one tablet.",
      ],
      hypo_advice: [
        "These are unlikely to cause low blood sugar on their own.",
        "If you feel shaky or sweaty, have some jelly beans.",
        "Watch out for signs of a hypo, like shakiness.",
        "Low blood sugar isn't common with these, but know the signs.",
        "These don't usually cause hypos on their own, but if you feel shaky have some sugar.",
        "If you get sweaty and shaky, that could be low blood sugar.",
        "if u feel shaky have some sugar",
        "These medicines rarely cause hypoglycaemia on their own, but be aware of symptoms such as sweating or shakiness.",
        "Low blood sugar isn't common with these, but if you feel shaky have something sugary.",
        "Watch for signs of a hypo like sweating or shakiness.",
      ],
      diabetes_red_flags: [
        "If you get severe stomach pain going through to your back, get urgent help.",
        "Any swelling of your face or lips, seek medical help straight away.",
        "Stop the tablets and see a doctor if you get bad abdominal pain.",
        "Severe tummy pain needs urgent medical attention.",
        "If you get bad stomach pain that goes through to your back, go to hospital.",
        "Swelling of the lips or face needs urgent help.",
        "bad stomach pain go to hospital",
        "Seek urgent medical attention for severe abdominal pain or facial swelling.",
        "Severe stomach pain going to your back needs urgent medical help.",
        "If your face or lips swell, seek help immediately.",
      ],
    },
    mustNot: {
      metformin_gi_advice: ["It doesn't matter whether you take the metformin with food."],
      metformin_xr_admin: ["You can halve them if they're too big to swallow."],
      sitagliptin_dose: ["Take two sitagliptin tablets a day."],
    },
  },
};
